const $=id=>document.getElementById(id),canvas=$('story'),ctx=canvas.getContext('2d');
const promoFields=['promoKicker','promoHeading1','promoHeading2','promoHeading3','promoBenefit1Title','promoBenefit1Desc','promoBenefit2Title','promoBenefit2Desc','promoBenefit3Title','promoBenefit3Desc','promoBenefit4Title','promoBenefit4Desc','promoBenefit5Title','promoBenefit5Desc','promoBenefit6Title','promoBenefit6Desc','promoBenefit7Title','promoBenefit7Desc','promoBenefit8Title','promoBenefit8Desc','promoStockTitle','promoTelegram','promoAvito','promoSlogan','promoContact'];
const extraPromoFields=['promoStyle','fastKicker','fastTitle','fastSubtitle','fastStep1','fastStep2','fastStep3','fastCta','tradeKicker','tradeTitle','tradeSubtitle','tradePoint1','tradePoint2','tradePoint3','tradeCta','creditKicker','creditTitle','creditSubtitle','creditPoint1','creditPoint2','creditPoint3','creditCta','stockKicker','stockTitle','stockSubtitle','stockTelegram','stockAvito','stockCta'];
const fields=['sourceText','model','year','mileage','price','salePrice','purchaseOption','features','location','phone','cta','soldStatus','soldDays','soldSubtitle','soldDurationPrefix','soldCta',...promoFields,...extraPromoFields];
const settingFields=['collageLayout','collageCount','palettePreset','textPreset','soldTextPreset','brandColor','accentColor','backgroundColor','logoCaption','arrivalLabel'];
const checkboxFields=['showLogo','showLogoCaption','showArrivalLabel','yearInMileage','soldMode'];
const benefitToggleFields=Array.from({length:8},(_,i)=>`promoBenefit${i+1}`);
const toggleFields=['model','year','mileage','price','salePrice','purchaseOption','features','location','phone','cta',...promoFields.filter(id=>!/^promoBenefit/.test(id)),...extraPromoFields.filter(id=>id!=='promoStyle'),...benefitToggleFields];
const palettes={brand:['#E53935','#FF4D4D','#0A0A0A'],graphite:['#E53935','#9AA0A8','#111214'],navy:['#E53935','#4D8DFF','#071426'],sand:['#E53935','#D7B377','#17130F'],teal:['#E53935','#2BC2AE','#061716'],violet:['#E53935','#A47AFF','#120C1C'],strictPremium:['#1A3B5D','#D4AF37','#0A0A0A'],urbanDrive:['#3A3F4E','#00CED1','#0F1115'],warmComfort:['#4B5320','#FFD700','#121212'],elegantReserve:['#2C3E50','#95A5A6','#0B0B0B'],freshStart:['#34495E','#2ECC71','#101214'],businessBenefit:['#2B2D33','#F1C40F','#0D0D0D'],brightAccent:['#363C45','#E67E22','#111316'],energyPulse:['#2F4F4F','#FF9F1C','#0C0C0C'],clearSignal:['#1E272E','#00E5FF','#0E1013'],transparentDeal:['#4A657E','#27AE60','#0F1014'],calmConfidence:['#5B656B','#8E44AD','#131518'],festiveSuccess:['#2C3E50','#FEDD61','#090B0D'],lightCelebration:['#34495E','#3498DB','#0A0C0F'],offroadReliability:['#4B5320','#C0392B','#14161A'],techMinimalism:['#1C2833','#1ABC9C','#08090A'],retroStyle:['#566573','#D35400','#15171B'],sportPulse:['#2E4053','#E74C3C','#070809']};
const textPresets={default:{arrivalLabel:'НОВОЕ ПОСТУПЛЕНИЕ',cta:'Не откладывайте: хорошие варианты долго не задерживаются. Пишите или звоните — записывайтесь на осмотр.'},benefit:{arrivalLabel:'ВЫГОДНОЕ ПРЕДЛОЖЕНИЕ',cta:'Специальные условия на этот автомобиль. Напишите — расскажем подробности и запишем на осмотр.'},urgent:{arrivalLabel:'СРОЧНАЯ ПРОДАЖА',cta:'Автомобиль готов к сделке. Если вариант подходит — лучше не откладывать осмотр.'},commission:{arrivalLabel:'КОМИССИОННАЯ ПРОДАЖА',cta:'Проверим автомобиль, ответим на вопросы и организуем удобный осмотр.'},calm:{arrivalLabel:'АВТОМОБИЛЬ В НАЛИЧИИ',cta:'Напишите или позвоните — спокойно расскажем об автомобиле и договоримся об осмотре.'}};
const soldTextPresets={sold:{soldStatus:'ПРОДАНО',soldSubtitle:'Этот автомобиль уже нашёл нового владельца',soldDurationPrefix:'Реализован за',soldCta:'Не нашли свой автомобиль? Подберём похожий или покажем варианты в наличии'},realized:{soldStatus:'РЕАЛИЗОВАНО',soldSubtitle:'Сделка успешно завершена — автомобиль передан владельцу',soldDurationPrefix:'Реализован за',soldCta:'Хотите такой же результат? Подберём автомобиль или поможем продать ваш'},fomo:{soldStatus:'ПРОДАНО',soldSubtitle:'Хороший вариант долго не задержался',soldDurationPrefix:'Продан за',soldCta:'Если автомобиль нравится — лучше не откладывать. Покажем похожие варианты в наличии'}};
const DEFAULT_CTA='Не откладывайте: средний срок продажи — 2 недели. Пишите, звоните за подробностями — записывайтесь на осмотр.';
const state={photos:[],page:0,slot:0,logos:{dark:null,light:null},drag:null,pointers:new Map(),pinch:null,dragIndex:null,exporting:false,archiveRoot:null,projectDir:null,projectId:null,archiveBusy:false,photoBusy:false,workMode:'single',batchActiveId:null,batchBusy:false,batchDirty:false,singleDraft:null,defaultEditor:null};
const platform={embedded:new URLSearchParams(location.search).get('embedded')==='1',vehicle:null,company:null,storageKey:'titan-story-data',seq:0,pending:new Map()};
function theme(){return{brand:$('brandColor').value,accent:$('accentColor').value,bg:$('backgroundColor').value}}
function alpha(hex,a){return hex+Math.round(a*255).toString(16).padStart(2,'0')}
function toggleId(id){return 'show-'+id}
function isOn(id){return $(toggleId(id))?.checked!==false}
function fieldValue(id){return isOn(id)?$(id).value:''}
function setupFieldToggles(){document.querySelectorAll('.promo-settings .field').forEach(field=>{const control=field.querySelector(':scope > input, :scope > textarea');if(control?.id)field.dataset.toggle=control.id});document.querySelectorAll('.field[data-toggle]').forEach(original=>{let field=original;if(original.tagName==='LABEL'){field=document.createElement('div');field.className=original.className;field.dataset.toggle=original.dataset.toggle;while(original.firstChild)field.appendChild(original.firstChild);original.replaceWith(field)}const id=field.dataset.toggle,title=field.querySelector(':scope > span'),input=document.createElement('input'),wrap=document.createElement('span');input.type='checkbox';input.id=toggleId(id);input.checked=true;input.setAttribute('aria-label',`Показывать поле ${title.textContent}`);wrap.className='field-toggle';wrap.append(input,document.createTextNode(' вкл.'));title.append(wrap);input.addEventListener('change',()=>{field.classList.toggle('is-off',!input.checked);save();draw()})});document.querySelectorAll('.promo-benefit-grid fieldset').forEach((fieldset,i)=>{const id=`promoBenefit${i+1}`,input=document.createElement('input'),wrap=document.createElement('span');input.type='checkbox';input.id=toggleId(id);input.checked=true;wrap.className='field-toggle benefit-toggle';wrap.append(input,document.createTextNode(' вкл.'));fieldset.querySelector('legend').append(wrap);input.addEventListener('change',()=>{fieldset.classList.toggle('is-off',!input.checked);save();draw()})})}
function syncSettingsUi(){document.querySelectorAll('.field[data-toggle]').forEach(f=>f.classList.toggle('is-off',!isOn(f.dataset.toggle)));document.querySelectorAll('.promo-benefit-grid fieldset').forEach((f,i)=>f.classList.toggle('is-off',!isOn(`promoBenefit${i+1}`)));$('logoCaption').disabled=!$('showLogoCaption').checked;$('logoCaption').closest('.control-field').classList.toggle('is-disabled',!$('showLogoCaption').checked);$('arrivalLabel').disabled=!$('showArrivalLabel').checked;$('arrivalLabel').closest('.control-field').classList.toggle('is-disabled',!$('showArrivalLabel').checked);$('soldFields').classList.toggle('active',$('soldMode').checked);$('soldMode').closest('.status-settings').classList.toggle('is-sold',$('soldMode').checked)}
function clean(s){return s.replace(/[🚙✅📍💸📱*]/gu,'').replace(/\s+/g,' ').trim()}
function parseAd(){const raw=$('sourceText').value,lines=raw.split(/\n+/).map(clean).filter(Boolean),phone=raw.match(/(?:\+7|8)[\d\s()-]{10,}/)?.[0]?.trim(),priceLine=lines.find(x=>/цен[аы]|₽|руб/i.test(x)),yearLine=lines.find(x=>/\b(?:19|20)\d{2}\b/.test(x)),mileageLine=lines.find(x=>/(?:т\.?\s*км|тыс|пробег|\bкм\b)/i.test(x)),locationLine=lines.find(x=>/забирать|самар|город|находится/i.test(x)),excluded=new Set([priceLine,yearLine,mileageLine,locationLine,phone&&lines.find(x=>x.includes(phone))].filter(Boolean)),modelLine=lines.find(x=>!excluded.has(x)&&!/^цена|^тел/i.test(x))||'',candidates=lines.filter(x=>x!==modelLine&&!excluded.has(x)&&!/(?:\+7|^8[\s(])/i.test(x));$('model').value=modelLine.toUpperCase().slice(0,32);$('year').value=yearLine?.match(/(?:19|20)\d{2}/)?.[0]||'';$('mileage').value=mileageLine?formatMileage(mileageLine):'';$('price').value=priceLine?formatPrice(priceLine):'';$('features').value=candidates.slice(0,6).map(x=>x.toUpperCase()).join('\n');$('location').value='Самара · Мирная, 3, корпус 1';$('phone').value='+7 927 265 17 77';save();draw();toast('Текст разобран — проверьте поля')}
function formatMileage(s){const n=s.match(/[\d\s]+/)?.[0]?.trim()||'';return /т\.?\s*км|тыс/i.test(s)?n.replace(/\s/g,'')+' 000 км':n+' км'}
function formatPrice(s){const digits=s.replace(/[^\d]/g,'');return digits?Number(digits).toLocaleString('ru-RU')+' ₽':clean(s)}
function loadImage(src){return new Promise((resolve,reject)=>{const im=new Image;im.onload=()=>resolve(im);im.onerror=reject;im.src=src})}
function recolorLogoData(data,color){const base64=data.split(',')[1],svg=decodeURIComponent(escape(atob(base64))),changed=svg.replace(/fill:#080808;stroke:#080808/g,`fill:${color};stroke:${color}`);return 'data:image/svg+xml;base64,'+btoa(unescape(encodeURIComponent(changed)))}
async function loadBundledLogos(){if(!window.TITAN_LOGO_DATA)throw new Error('Данные логотипа не найдены');const [dark,light]=await Promise.all([loadImage(window.TITAN_LOGO_DATA),loadImage(recolorLogoData(window.TITAN_LOGO_DATA,'#ffffff'))]);return{dark,light}}
async function init(){setupFieldToggles();state.defaultEditor=collectEditorData();restore();syncSettingsUi();updatePromoPanel();setupBatchUi();if(matchMedia('(min-width:901px)').matches){window.scrollTo(0,0);document.documentElement.scrollTop=0;document.body.scrollTop=0}try{state.logos=await loadBundledLogos()}catch(e){console.warn(e.message)}updateCount();draw()}
const nextFrame=()=>new Promise(resolve=>requestAnimationFrame(()=>resolve()));
function formatBytes(bytes){if(bytes<1024*1024)return`${Math.max(1,Math.round(bytes/1024))} КБ`;return`${(bytes/1024/1024).toFixed(1).replace('.',',')} МБ`}
function setPhotoBusy(busy,text='Тяжёлые фото оптимизируются автоматически'){state.photoBusy=busy;$('photos').disabled=busy;$('photoStatus').textContent=text;$('photos').closest('.upload-box').classList.toggle('is-processing',busy)}
async function decodePhoto(file){if('createImageBitmap'in window){try{return await createImageBitmap(file,{imageOrientation:'from-image'})}catch(e){console.warn('createImageBitmap:',e.message)}}const url=URL.createObjectURL(file);try{return await loadImage(url)}finally{URL.revokeObjectURL(url)}}
let photoWorker=null,photoWorkerSeq=0;const photoWorkerJobs=new Map();
function getPhotoWorker(){if(photoWorker)return photoWorker;if(!window.Worker||!window.OffscreenCanvas||!window.createImageBitmap)return null;const code=`self.onmessage=async({data})=>{const{id,file,maxSide,quality}=data;try{const source=await createImageBitmap(file,{imageOrientation:'from-image'}),sw=source.width,sh=source.height,scale=Math.min(1,maxSide/Math.max(sw,sh)),width=Math.max(1,Math.round(sw*scale)),height=Math.max(1,Math.round(sh*scale)),surface=new OffscreenCanvas(width,height),ctx=surface.getContext('2d',{alpha:false});ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(source,0,0,width,height);source.close();const blob=await surface.convertToBlob({type:'image/jpeg',quality});self.postMessage({id,blob,width,height})}catch(error){self.postMessage({id,error:error?.message||String(error)})}}`;const url=URL.createObjectURL(new Blob([code],{type:'text/javascript'}));photoWorker=new Worker(url);URL.revokeObjectURL(url);photoWorker.onmessage=({data})=>{const job=photoWorkerJobs.get(data.id);if(!job)return;photoWorkerJobs.delete(data.id);data.error?job.reject(new Error(data.error)):job.resolve(data)};photoWorker.onerror=e=>{photoWorkerJobs.forEach(job=>job.reject(new Error(e.message||'Ошибка фоновой обработки')));photoWorkerJobs.clear();photoWorker.terminate();photoWorker=null};return photoWorker}
function optimizeInWorker(file){const worker=getPhotoWorker();if(!worker)return Promise.reject(new Error('worker-unavailable'));return new Promise((resolve,reject)=>{const id=++photoWorkerSeq;photoWorkerJobs.set(id,{resolve,reject});worker.postMessage({id,file,maxSide:2560,quality:.88})})}
async function optimizeOnMain(file){const source=await decodePhoto(file),sw=source.width||source.naturalWidth,sh=source.height||source.naturalHeight;if(!sw||!sh)throw new Error('не удалось определить размер');const scale=Math.min(1,2560/Math.max(sw,sh)),width=Math.max(1,Math.round(sw*scale)),height=Math.max(1,Math.round(sh*scale)),surface=document.createElement('canvas');surface.width=width;surface.height=height;const c=surface.getContext('2d',{alpha:false});c.imageSmoothingEnabled=true;c.imageSmoothingQuality='high';c.drawImage(source,0,0,width,height);if(source.close)source.close();const blob=await new Promise((resolve,reject)=>surface.toBlob(b=>b?resolve(b):reject(new Error('не удалось сжать фото')),'image/jpeg',.88));return{blob,width,height}}
async function optimizedPhoto(file){let result;try{result=await optimizeInWorker(file)}catch(e){console.warn('Фоновая оптимизация недоступна:',e.message);result=await optimizeOnMain(file)}const{blob,width,height}=result,base=(file.name||'photo').replace(/\.[^.]+$/,'')||'photo',optimized=new File([blob],`${base}-optimized.jpg`,{type:'image/jpeg',lastModified:Date.now()}),url=URL.createObjectURL(optimized),img=await loadImage(url);return{file:optimized,url,img,sourceName:file.name||'Фото',sourceSize:file.size||0,optimizedSize:optimized.size,width,height,collage:{x:0,y:0,zoom:1},single:{x:0,y:0,zoom:1}}}
async function addPhotos(files){let queue=[...files];if(!queue.length||state.photoBusy)return;if(state.workMode==='batch'){const room=Math.max(0,7-state.photos.length);if(!room){toast('Для одного автомобиля можно добавить до 7 фото');$('photos').value='';return}if(queue.length>room){queue=queue.slice(0,room);toast(`Добавлены первые ${room} фото — лимит 7 на автомобиль`)}}setPhotoBusy(true,`Подготовка: 0 / ${queue.length}`);let added=0;for(let i=0;i<queue.length;i++){setPhotoBusy(true,`Оптимизация фото ${i+1} из ${queue.length}…`);await nextFrame();try{state.photos.push(await optimizedPhoto(queue[i]));added++;renderThumbs();draw()}catch(e){console.error(e);toast(`Не удалось открыть ${queue[i].name}: ${e.message}`)}await nextFrame()}if(added)save();setPhotoBusy(false,added?`Готово: ${added} фото оптимизировано`:'Не удалось обработать выбранные фото');$('photos').value='';setTimeout(()=>{if(!state.photoBusy)$('photoStatus').textContent='Тяжёлые фото оптимизируются автоматически'},3500)}
function vehiclePages(){return Math.max(1,state.photos.length)}
function pages(){return vehiclePages()+1}
function isPromoPage(page=state.page){return page===pages()-1}
function renderThumbs(){$('photoList').innerHTML='';const collageTotal=Number($('collageCount').value);state.photos.forEach((p,i)=>{const d=document.createElement('div');d.className='thumb '+(i===state.slot?'active':'')+(p.sourceSize?' has-meta':'');d.dataset.number=i+1;d.draggable=true;const saving=p.sourceSize&&p.optimizedSize?Math.max(0,Math.round((1-p.optimizedSize/p.sourceSize)*100)):0;d.innerHTML=`<img src="${p.url}" alt="Фото ${i+1}"><button type="button" aria-label="Удалить">×</button>${p.sourceSize?`<span class="photo-meta">${formatBytes(p.optimizedSize)}${saving?` · −${saving}%`:''}</span>`:''}`;d.onclick=e=>{if(e.target.tagName==='BUTTON'){URL.revokeObjectURL(p.url);state.photos.splice(i,1);state.slot=Math.max(0,Math.min(state.slot,state.photos.length-1));state.page=Math.min(state.page,pages()-1);save();renderThumbs();draw();return}state.slot=i;if(i>=collageTotal)state.page=i;renderThumbs();draw()};d.ondragstart=()=>{state.dragIndex=i;d.classList.add('dragging')};d.ondragend=()=>d.classList.remove('dragging');d.ondragover=e=>e.preventDefault();d.ondrop=e=>{e.preventDefault();if(state.dragIndex===null||state.dragIndex===i)return;const moved=state.photos.splice(state.dragIndex,1)[0];state.photos.splice(i,0,moved);state.slot=i;state.dragIndex=null;save();renderThumbs();draw()};$('photoList').append(d)});updateCount()}
function updateCount(){const n=pages();$('pageCount').textContent=`${state.page+1} / ${n}`;$('prevBtn').disabled=state.page<=0;$('nextBtn').disabled=state.page>=n-1}
function roundRect(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function fitText(text,maxWidth,start,min=30,font='Montserrat',weight=900){let size=start;do{ctx.font=`${weight} ${size}px ${font}`;size-=2}while(ctx.measureText(text).width>maxWidth&&size>min);return size+2}
function drawCover(img,x,y,w,h,t){const scale=Math.max(w/img.width,h/img.height)*t.zoom,dw=img.width*scale,dh=img.height*scale;ctx.save();ctx.beginPath();ctx.rect(x,y,w,h);ctx.clip();ctx.filter='contrast(1.08) saturate(.88) brightness(.88)';ctx.drawImage(img,x+(w-dw)/2+t.x,y+(h-dh)/2+t.y,dw,dh);ctx.restore()}
function splitGrid(x,y,w,h,count,cols=Math.ceil(Math.sqrt(count)),gap=3){const rows=Math.ceil(count/cols),rects=[];for(let i=0;i<count;i++){const row=Math.floor(i/cols),col=i%cols,rowCount=Math.min(cols,count-row*cols),cw=(w-gap*(rowCount-1))/rowCount,ch=(h-gap*(rows-1))/rows;rects.push({x:x+col*(cw+gap),y:y+row*(ch+gap),w:cw,h:ch})}return rects}
function collageRects(){const count=Number($('collageCount').value),layout=$('collageLayout').value,g=3,W=1080,H=1248;if(layout==='grid')return splitGrid(0,0,W,H,count,count<=4?2:3,g);if(layout==='hero'){const heroH=690;return[{x:0,y:0,w:W,h:heroH},...splitGrid(0,heroH+g,W,H-heroH-g,count-1,count<=4?count-1:3,g)]}if(layout==='columns'){const heroW=650;return[{x:0,y:0,w:heroW,h:H},...splitGrid(heroW+g,0,W-heroW-g,H,count-1,count<=4?1:2,g)]}if(count===6)return[{x:0,y:0,w:777,h:831},{x:780,y:0,w:300,h:414},{x:780,y:417,w:300,h:414},{x:780,y:834,w:300,h:414},{x:0,y:834,w:387,h:414},{x:390,y:834,w:387,h:414}];const rightCount=Math.ceil((count-1)/2),bottomCount=count-1-rightCount,heroW=777,topH=831,rects=[{x:0,y:0,w:heroW,h:topH},...splitGrid(heroW+g,0,W-heroW-g,topH,rightCount,1,g)];if(bottomCount)rects.push(...splitGrid(0,topH+g,W,H-topH-g,bottomCount,bottomCount,g));return rects}
function placeholder(r){ctx.fillStyle='#191919';ctx.fillRect(r.x,r.y,r.w,r.h);ctx.fillStyle='#555';ctx.font='600 24px Inter';ctx.textAlign='center';ctx.fillText('+ ФОТО',r.x+r.w/2,r.y+r.h/2);ctx.textAlign='left'}
function drawPhotos(){if(state.page===0){const rects=collageRects();rects.forEach((r,i)=>state.photos[i]?drawCover(state.photos[i].img,r.x,r.y,r.w,r.h,state.photos[i].collage):placeholder(r));if(!state.exporting&&state.photos[state.slot]&&state.slot<rects.length){const r=rects[state.slot];ctx.strokeStyle=theme().accent;ctx.lineWidth=5;ctx.strokeRect(r.x+3,r.y+3,r.w-6,r.h-6)}}else{const p=state.photos[state.page];p?drawCover(p.img,0,0,1080,1248,p.single):placeholder({x:0,y:0,w:1080,h:1248})}}
function logoBackgroundIsDark(){try{const data=ctx.getImageData(82,138,150,30).data;let sum=0,count=0;for(let i=0;i<data.length;i+=16){sum+=.2126*data[i]+.7152*data[i+1]+.0722*data[i+2];count++}return sum/Math.max(1,count)<145}catch{return true}}
function drawLogo(){const logo=logoBackgroundIsDark()?state.logos.light:state.logos.dark;if($('showLogo').checked&&logo){ctx.save();ctx.shadowColor=logo===state.logos.light?'rgba(0,0,0,.75)':'rgba(255,255,255,.35)';ctx.shadowBlur=14;ctx.drawImage(logo,120,280,1800,1450,72,68,174,120);ctx.restore()}if($('showLogoCaption').checked){ctx.save();ctx.fillStyle='#F5F5F5';ctx.shadowColor='rgba(0,0,0,.8)';ctx.shadowBlur=8;ctx.font=`700 ${fitText($('logoCaption').value,440,21,15,'Inter',700)}px Inter`;ctx.fillText($('logoCaption').value,72,218);ctx.restore()}}
function wrapText(text,maxWidth,maxLines=2){const words=text.split(/\s+/),lines=[];let line='';for(const word of words){const test=(line+' '+word).trim();if(ctx.measureText(test).width<=maxWidth||!line)line=test;else{lines.push(line);line=word;if(lines.length===maxLines-1)break}}if(line&&lines.length<maxLines)lines.push(line);return lines}
function drawPromoClassic(){
  const t=theme(),g=ctx.createRadialGradient(900,160,20,620,500,1050);g.addColorStop(0,alpha(t.accent,.34));g.addColorStop(.55,alpha(t.brand,.12));g.addColorStop(1,t.bg);ctx.fillStyle=g;ctx.fillRect(0,0,1080,1920);
  ctx.strokeStyle=alpha(t.accent,.18);ctx.lineWidth=2;for(let y=250;y<1700;y+=150){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(1080,y-280);ctx.stroke()}
  const kicker=fieldValue('promoKicker'),heading1=fieldValue('promoHeading1'),heading2=fieldValue('promoHeading2'),heading3=fieldValue('promoHeading3');drawLogo();ctx.fillStyle=t.accent;ctx.font=`700 ${fitText(kicker,936,25,18,'Inter',700)}px Inter`;ctx.fillText(kicker,72,325);
  ctx.fillStyle='#fff';ctx.font=`900 ${fitText(heading1,936,72,46)}px Montserrat`;ctx.fillText(heading1,72,425);ctx.font=`900 ${fitText(heading2,936,72,46)}px Montserrat`;ctx.fillText(heading2,72,505);ctx.fillStyle=t.accent;ctx.font=`900 ${fitText(heading3,936,58,40)}px Montserrat`;ctx.fillText(heading3,72,575);
  const benefits=Array.from({length:8},(_,i)=>[$(`promoBenefit${i+1}Title`).value,$(`promoBenefit${i+1}Desc`).value]);
  benefits.forEach((b,i)=>{if(!isOn(`promoBenefit${i+1}`))return;const col=i%2,row=Math.floor(i/2),x=72+col*476,y=655+row*142,w=460,h=124;ctx.fillStyle='rgba(255,255,255,.045)';roundRect(x,y,w,h,22);ctx.fill();ctx.fillStyle=t.brand;ctx.fillRect(x,y,7,h);const size=fitText(b[0],386,23,17,'Montserrat',800);ctx.fillStyle='#fff';ctx.font=`800 ${size}px Montserrat`;ctx.fillText(b[0],x+32,y+47);ctx.fillStyle='#A0A0A0';ctx.font='500 19px Inter';wrapText(b[1],390,2).forEach((line,j)=>ctx.fillText(line,x+32,y+80+j*22))});
  const stockTitle=fieldValue('promoStockTitle'),telegram=fieldValue('promoTelegram'),avito=fieldValue('promoAvito'),slogan=fieldValue('promoSlogan'),contact=fieldValue('promoContact');ctx.fillStyle=alpha(t.accent,.13);roundRect(72,1255,936,166,24);ctx.fill();ctx.strokeStyle=alpha(t.accent,.38);ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#fff';ctx.font=`800 ${fitText(stockTitle,864,27,19,'Montserrat',800)}px Montserrat`;ctx.fillText(stockTitle,108,1305);ctx.fillStyle=t.accent;ctx.font=`800 ${fitText(telegram,864,34,23,'Inter',800)}px Inter`;ctx.fillText(telegram,108,1355);ctx.fillStyle='#D5D5D5';ctx.font=`600 ${fitText(avito,864,22,16,'Inter',600)}px Inter`;ctx.fillText(avito,108,1393);
  ctx.fillStyle=t.accent;ctx.font=`800 ${fitText(slogan,936,27,19,'Inter',800)}px Inter`;ctx.fillText(slogan,72,1510);ctx.fillStyle='#fff';ctx.font=`800 ${fitText(contact,936,34,23,'Inter',800)}px Inter`;ctx.fillText(contact,72,1580);drawPromoFooter(1700);
}
function promoBg(mode=0){const t=theme();ctx.fillStyle=t.bg;ctx.fillRect(0,0,1080,1920);const g=ctx.createRadialGradient(mode?160:900,mode?280:180,20,540,620,1050);g.addColorStop(0,alpha(t.accent,.4));g.addColorStop(1,alpha(t.bg,0));ctx.fillStyle=g;ctx.fillRect(0,0,1080,1450);ctx.strokeStyle=alpha(t.accent,.16);ctx.lineWidth=2;for(let i=-500;i<1900;i+=170){ctx.beginPath();ctx.moveTo(0,i);ctx.lineTo(1080,i+(mode?-360:360));ctx.stroke()}drawLogo()}
function promoText(id,x,y,max,size,color='#fff',weight=900){const value=fieldValue(id);if(!value)return;ctx.fillStyle=color;ctx.font=`${weight} ${fitText(value,max,size,24,'Montserrat',weight)}px Montserrat`;ctx.fillText(value,x,y)}
function drawPromoFooter(y=1740){ctx.fillStyle='#F5F5F5';ctx.font='600 23px Inter';if(isOn('location'))ctx.fillText($('location').value||'Самара · Мирная, 3, корпус 1',72,y);ctx.textAlign='right';if(isOn('phone'))ctx.fillText($('phone').value||'+7 927 265 17 77',1008,y);ctx.textAlign='left'}
function drawPromoFast(){const t=theme();promoBg();promoText('fastKicker',72,340,936,27,t.accent,700);promoText('fastTitle',72,510,900,70);ctx.fillStyle='#bbb';ctx.font='500 29px Inter';wrapText(fieldValue('fastSubtitle'),870,3).forEach((l,i)=>ctx.fillText(l,72,600+i*38));['fastStep1','fastStep2','fastStep3'].forEach((id,i)=>{const y=820+i*205;if(!isOn(id))return;ctx.fillStyle=t.brand;ctx.beginPath();ctx.arc(130,y,58,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.font='900 45px Montserrat';ctx.textAlign='center';ctx.fillText(i+1,130,y+16);ctx.textAlign='left';promoText(id,230,y+12,760,36,'#fff',800)});promoText('fastCta',72,1560,936,38,t.accent,800);drawPromoFooter()}
function drawPromoTrade(){const t=theme();promoBg(1);promoText('tradeKicker',72,340,936,27,t.accent,700);promoText('tradeTitle',72,520,920,68);ctx.fillStyle='#c7c7c7';ctx.font='500 29px Inter';wrapText(fieldValue('tradeSubtitle'),900,3).forEach((l,i)=>ctx.fillText(l,72,615+i*39));ctx.strokeStyle=t.brand;ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(155,870);ctx.lineTo(880,870);ctx.stroke();ctx.fillStyle=t.brand;ctx.beginPath();ctx.moveTo(880,820);ctx.lineTo(990,870);ctx.lineTo(880,920);ctx.fill();['tradePoint1','tradePoint2','tradePoint3'].forEach((id,i)=>{if(!isOn(id))return;const y=1050+i*125;ctx.fillStyle='#fff';ctx.font='800 32px Inter';ctx.fillText('✓',82,y);promoText(id,145,y,820,31,'#fff',700)});promoText('tradeCta',72,1550,936,37,t.accent,800);drawPromoFooter()}
function drawPromoCredit(){const t=theme();promoBg();promoText('creditKicker',72,340,936,27,t.accent,700);promoText('creditTitle',72,520,920,68);ctx.fillStyle='#c7c7c7';ctx.font='500 29px Inter';wrapText(fieldValue('creditSubtitle'),900,3).forEach((l,i)=>ctx.fillText(l,72,615+i*39));['creditPoint1','creditPoint2','creditPoint3'].forEach((id,i)=>{if(!isOn(id))return;const x=72+i*312,y=870,w=286,h=360;ctx.fillStyle='rgba(255,255,255,.06)';roundRect(x,y,w,h,28);ctx.fill();ctx.fillStyle=t.brand;ctx.font='900 58px Montserrat';ctx.fillText('0'+(i+1),x+30,y+88);ctx.fillStyle='#fff';ctx.font='800 27px Inter';wrapText(fieldValue(id),w-60,4).forEach((l,j)=>ctx.fillText(l,x+30,y+170+j*38))});promoText('creditCta',72,1510,936,37,t.accent,800);drawPromoFooter()}
function drawPromoStock(){const t=theme();promoBg(1);promoText('stockKicker',72,330,936,27,t.accent,700);promoText('stockTitle',72,515,920,68);ctx.fillStyle='#c7c7c7';ctx.font='500 29px Inter';wrapText(fieldValue('stockSubtitle'),900,3).forEach((l,i)=>ctx.fillText(l,72,610+i*39));ctx.fillStyle=alpha(t.accent,.15);roundRect(72,830,936,330,35);ctx.fill();promoText('stockTelegram',115,940,850,45,'#fff',800);promoText('stockAvito',115,1050,850,31,'#ddd',700);ctx.fillStyle=t.brand;roundRect(72,1300,936,190,30);ctx.fill();promoText('stockCta',115,1415,850,39,'#fff',800);drawPromoFooter()}
function soldDuration(){const days=$('soldDays').value.trim(),n=Number(days),word=n%10===1&&n%100!==11?'день':[2,3,4].includes(n%10)&&![12,13,14].includes(n%100)?'дня':'дней';return[$('soldDurationPrefix').value.trim(),days,days?word:''].filter(Boolean).join(' ')}
function drawSoldPromo(){const t=theme(),status=($('soldStatus').value||'ПРОДАНО').toUpperCase(),model=($('model').value||'АВТОМОБИЛЬ').toUpperCase(),duration=soldDuration();promoBg(1);ctx.fillStyle=t.accent;ctx.font='800 25px Inter';ctx.fillText('УСПЕШНАЯ СДЕЛКА · ТИТАН АВТО',72,330);ctx.fillStyle='#fff';ctx.font=`900 ${fitText(status,936,98,62)}px Montserrat`;ctx.fillText(status,72,475);ctx.fillStyle='#e8e8e8';ctx.font=`900 ${fitText(model,936,55,34)}px Montserrat`;ctx.fillText(model,72,555);ctx.fillStyle='#bbb';ctx.font='500 29px Inter';wrapText($('soldSubtitle').value,900,2).forEach((line,i)=>ctx.fillText(line,72,625+i*38));ctx.fillStyle=t.brand;roundRect(72,760,620,120,28);ctx.fill();ctx.fillStyle='#fff';ctx.font=`800 ${fitText(duration,550,43,27,'Montserrat',800)}px Montserrat`;ctx.fillText(duration,108,835);ctx.fillStyle='rgba(255,255,255,.06)';roundRect(72,1000,936,310,32);ctx.fill();ctx.fillStyle=t.accent;ctx.font='800 28px Inter';ctx.fillText('ИЩЕТЕ СВОЙ АВТОМОБИЛЬ?',112,1070);ctx.fillStyle='#fff';ctx.font='700 34px Inter';wrapText($('soldCta').value,850,4).forEach((line,i)=>ctx.fillText(line,112,1140+i*44));ctx.fillStyle=t.brand;roundRect(72,1410,936,150,28);ctx.fill();ctx.fillStyle='#fff';ctx.font='800 31px Inter';ctx.fillText('ПОКАЖЕМ ВАРИАНТЫ В НАЛИЧИИ',112,1472);ctx.font='600 24px Inter';ctx.fillText('или подберём похожий автомобиль под ваш запрос',112,1518);drawPromoFooter(1740)}
function drawPromo(){if($('soldMode')?.checked){drawSoldPromo();return}const style=$('promoStyle')?.value||'1';({1:drawPromoClassic,2:drawPromoFast,3:drawPromoTrade,4:drawPromoCredit,5:drawPromoStock}[style]||drawPromoClassic)()}
function updatePromoPanel(){const style=$('promoStyle')?.value||'1';document.querySelectorAll('[data-promo-panel]').forEach(p=>p.classList.toggle('active',p.dataset.promoPanel===style))}
function drawSoldStory(){
  const t=theme(),status=($('soldStatus').value||'ПРОДАНО').toUpperCase(),subtitle=$('soldSubtitle').value,duration=soldDuration();
  ctx.save();ctx.beginPath();ctx.rect(0,0,1080,1248);ctx.clip();ctx.fillStyle=alpha(t.bg,.38);ctx.fillRect(0,0,1080,1248);const photoFade=ctx.createLinearGradient(0,720,0,1248);photoFade.addColorStop(0,alpha(t.bg,0));photoFade.addColorStop(1,t.bg);ctx.fillStyle=photoFade;ctx.fillRect(0,720,1080,528);ctx.restore();drawLogo();
  ctx.fillStyle=t.accent;ctx.fillRect(72,1040,58,4);ctx.font=`800 ${fitText('СДЕЛКА ЗАВЕРШЕНА',820,25,18,'Inter',800)}px Inter`;ctx.fillText('СДЕЛКА ЗАВЕРШЕНА',150,1050);
  ctx.fillStyle='#fff';ctx.font=`900 ${fitText(status,936,104,64)}px Montserrat`;ctx.fillText(status,72,1215);ctx.fillStyle='#f2f2f2';ctx.font=`900 ${fitText(($('model').value||'АВТОМОБИЛЬ').toUpperCase(),936,55,35)}px Montserrat`;ctx.fillText(($('model').value||'АВТОМОБИЛЬ').toUpperCase(),72,1300);
  ctx.fillStyle='#c7c7c7';ctx.font='500 28px Inter';wrapText(subtitle,900,2).forEach((line,i)=>ctx.fillText(line,72,1360+i*36));if(duration){ctx.fillStyle=t.brand;roundRect(72,1450,520,94,22);ctx.fill();ctx.fillStyle='#fff';ctx.font=`800 ${fitText(duration,460,35,24,'Montserrat',800)}px Montserrat`;ctx.fillText(duration,102,1510)}
  ctx.fillStyle=t.accent;ctx.font='700 25px Inter';wrapText($('soldCta').value,936,3).forEach((line,i)=>ctx.fillText(line,72,1605+i*33));ctx.fillStyle='#F5F5F5';ctx.font='600 23px Inter';ctx.fillText($('location').value||'Самара · Мирная, 3, корпус 1',72,1772);ctx.textAlign='right';ctx.fillText($('phone').value||'+7 927 265 17 77',1008,1772);ctx.textAlign='left';updateCount();
}
function draw(){
  const t=theme();ctx.clearRect(0,0,1080,1920);ctx.fillStyle=t.bg;ctx.fillRect(0,0,1080,1920);if(isPromoPage()){drawPromo();updateCount();return}drawPhotos();if($('soldMode').checked){drawSoldStory();return}
  const grad=ctx.createLinearGradient(0,650,0,1330);grad.addColorStop(0,alpha(t.bg,0));grad.addColorStop(1,alpha(t.bg,.98));ctx.fillStyle=grad;ctx.fillRect(0,650,1080,700);drawLogo();
  const y=1188,arrival=$('arrivalLabel').value.trim();if($('showArrivalLabel').checked&&arrival){ctx.fillStyle=t.accent;ctx.font=`700 ${fitText(arrival.toUpperCase(),936,24,17,'Inter',700)}px Inter`;ctx.fillText(arrival.toUpperCase(),72,y)}
  const rawModel=($('model').value||'МОДЕЛЬ АВТО').toUpperCase(),rawYear=$('year').value.trim(),yearInMileage=$('yearInMileage').checked,visibleModel=isOn('model')?rawModel:'',visibleYear=isOn('year')&&!yearInMileage?rawYear:'',heading=(visibleModel+(visibleModel&&visibleYear?' · ':'')+visibleYear).trim(),layoutHeading=(rawModel+(rawYear?' · '+rawYear:'')).trim();
  const makeTitleLines=text=>{ctx.font='900 78px Montserrat';if(ctx.measureText(text).width<=936)return[text];const words=text.split(' ');let first='',second='';for(const word of words){if(!second&&ctx.measureText((first+' '+word).trim()).width<900)first=(first+' '+word).trim();else second=(second+' '+word).trim()}return[first,second].filter(Boolean)};
  const layoutTitleLines=makeTitleLines(layoutHeading),titleLines=heading?makeTitleLines(heading):[],titleSize=heading?(titleLines.length>1?58:fitText(heading,936,78,54)):78;ctx.fillStyle='#F5F5F5';ctx.font=`900 ${titleSize}px Montserrat`;titleLines.forEach((line,i)=>ctx.fillText(line,72,1270+i*64));
  let sy=1270+(layoutTitleLines.length-1)*64+58;const mileage=$('mileage').value.trim().replace(/^пробег\s*/i,''),mileageParts=[];if(isOn('year')&&yearInMileage&&rawYear)mileageParts.push(rawYear);if(isOn('mileage')&&mileage)mileageParts.push('Пробег '+mileage);ctx.fillStyle='#A0A0A0';ctx.font='600 31px Inter';if(mileageParts.length)ctx.fillText(mileageParts.join(' · '),72,sy);sy+=48;
  const feats=(isOn('features')?$('features').value:'').split(/\n/).map(clean).filter(Boolean).slice(0,6);ctx.font='600 28px Inter';const twoCols=feats.length>3||feats.some(f=>ctx.measureText(f.toUpperCase()).width>850),perCol=Math.ceil(feats.length/2),maxFeatureWidth=twoCols?410:875,featureSize=feats.length?Math.min(...feats.map(f=>fitText(f.toUpperCase(),maxFeatureWidth,28,20,'Inter',600))):28;feats.forEach((f,i)=>{const col=twoCols&&i>=perCol?1:0,row=twoCols?(col?i-perCol:i):i,x=72+col*470;ctx.fillStyle=t.brand;ctx.beginPath();ctx.arc(x+9,sy+row*42-9,6,0,Math.PI*2);ctx.fill();ctx.fillStyle='#F5F5F5';ctx.font=`600 ${featureSize}px Inter`;ctx.fillText(f.toUpperCase(),x+32,sy+row*42)});
  const money=v=>{const s=v.trim();return s&&!/₽|руб/i.test(s)?s+' ₽':s},rawPrice=money($('price').value)||'ЦЕНА ПО ЗАПРОСУ',price=isOn('price')?rawPrice:'',sale=isOn('salePrice')?money($('salePrice').value):'';if(price||sale){ctx.fillStyle='#A0A0A0';ctx.font='600 21px Inter';ctx.fillText('ЦЕНА',72,1550)}
  if(sale){const oldSize=fitText(rawPrice,350,32,24),newSize=fitText(sale,500,49,36);ctx.font=`700 ${oldSize}px Montserrat`;const oldWidth=ctx.measureText(rawPrice).width;if(price){ctx.fillStyle='#A0A0A0';ctx.fillText(price,72,1618);ctx.strokeStyle=t.brand;ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(68,1605);ctx.lineTo(80+oldWidth,1605);ctx.stroke()}ctx.font=`900 ${newSize}px Montserrat`;ctx.fillStyle='#fff';ctx.fillText(sale,72+oldWidth+48,1618)}else if(price){const ps=fitText(price,680,59,40);ctx.fillStyle='#fff';ctx.font=`900 ${ps}px Montserrat`;ctx.fillText(price,72,1620)}
  if(isOn('purchaseOption')){ctx.fillStyle='#fff';ctx.font='700 23px Inter';ctx.fillText($('purchaseOption').value||'Наличные · кредит · обмен с вашей/нашей доплатой',72,1665)}
  if(isOn('cta')){ctx.fillStyle=t.accent;ctx.font='700 23px Inter';wrapText($('cta').value||DEFAULT_CTA,936,2).forEach((line,i)=>ctx.fillText(line,72,1708+i*28))}
  ctx.fillStyle='#F5F5F5';ctx.font='600 23px Inter';if(isOn('location'))ctx.fillText($('location').value||'Самара · Мирная, 3, корпус 1',72,1772);ctx.textAlign='right';if(isOn('phone'))ctx.fillText($('phone').value||'+7 927 265 17 77',1008,1772);ctx.textAlign='left';updateCount();
}
function transformAt(x,y){if(isPromoPage())return null;if(state.page>0)return state.photos[state.page]?.single;const rects=collageRects(),i=rects.findIndex(r=>x>=r.x&&x<=r.x+r.w&&y>=r.y&&y<=r.y+r.h);if(i>=0&&state.photos[i]){state.slot=i;renderThumbs();return state.photos[i].collage}return null}
function filename(page=state.page){const base=`titan-auto-${($('model').value||'story').toLowerCase().replace(/[^a-zа-яё0-9]+/gi,'-')}`;return isPromoPage(page)?`${base}-final.png`:`${base}-${page+1}.png`}
function canvasBlob(){return new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('Не удалось создать PNG')),'image/png',1))}
function triggerDownload(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.style.display='none';document.body.appendChild(a);a.click();setTimeout(()=>{a.remove();URL.revokeObjectURL(url)},2500)}
async function downloadPage(page=state.page){const old=state.page;try{state.page=page;state.exporting=true;draw();const blob=await canvasBlob();triggerDownload(blob,filename(page));toast('Скачана текущая сторис')}catch(e){toast('Не удалось скачать: '+e.message)}finally{state.exporting=false;state.page=old;draw()}}
const crcTable=(()=>{const t=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xEDB88320^(c>>>1):c>>>1;t[n]=c>>>0}return t})();
function crc32(bytes){let c=0xFFFFFFFF;for(const b of bytes)c=crcTable[(c^b)&255]^(c>>>8);return(c^0xFFFFFFFF)>>>0}
function zipFiles(entries){const enc=new TextEncoder(),locals=[],centrals=[];let offset=0;for(const entry of entries){const name=enc.encode(entry.name),data=entry.data,crc=crc32(data),local=new Uint8Array(30+name.length+data.length),lv=new DataView(local.buffer);lv.setUint32(0,0x04034b50,true);lv.setUint16(4,20,true);lv.setUint16(6,0x800,true);lv.setUint32(14,crc,true);lv.setUint32(18,data.length,true);lv.setUint32(22,data.length,true);lv.setUint16(26,name.length,true);local.set(name,30);local.set(data,30+name.length);locals.push(local);const central=new Uint8Array(46+name.length),cv=new DataView(central.buffer);cv.setUint32(0,0x02014b50,true);cv.setUint16(4,20,true);cv.setUint16(6,20,true);cv.setUint16(8,0x800,true);cv.setUint32(16,crc,true);cv.setUint32(20,data.length,true);cv.setUint32(24,data.length,true);cv.setUint16(28,name.length,true);cv.setUint32(42,offset,true);central.set(name,46);centrals.push(central);offset+=local.length}const centralSize=centrals.reduce((s,x)=>s+x.length,0),end=new Uint8Array(22),ev=new DataView(end.buffer);ev.setUint32(0,0x06054b50,true);ev.setUint16(8,entries.length,true);ev.setUint16(10,entries.length,true);ev.setUint32(12,centralSize,true);ev.setUint32(16,offset,true);return new Blob([...locals,...centrals,end],{type:'application/zip'})}
async function downloadAll(){const old=state.page,files=[];try{state.exporting=true;for(let i=0;i<pages();i++){state.page=i;draw();const blob=await canvasBlob();files.push(new File([blob],filename(i),{type:'image/png'}))}if(navigator.share&&navigator.canShare?.({files})){await navigator.share({files,title:'Сторис ТИТАН АВТО'});toast(`Готово: ${files.length} сторис`)}else{files.forEach((file,i)=>setTimeout(()=>triggerDownload(file,file.name),i*350));toast(`Сохраняются ${files.length} PNG`)}}catch(e){if(e.name!=='AbortError')toast('Не удалось сохранить: '+e.message)}finally{state.exporting=false;state.page=old;draw()}}
function collectEditorData(){const d={};fields.forEach(id=>d[id]=$(id).value);settingFields.forEach(id=>d[id]=$(id).value);checkboxFields.forEach(id=>d[id]=$(id).checked);toggleFields.forEach(id=>d[toggleId(id)]=$(toggleId(id)).checked);return d}
function applyEditorData(d={}){fields.forEach(id=>{if(d[id]!=null)$(id).value=d[id]});settingFields.forEach(id=>{if(d[id]!=null)$(id).value=d[id]});checkboxFields.forEach(id=>{if(typeof d[id]==='boolean')$(id).checked=d[id]});toggleFields.forEach(id=>{if(typeof d[toggleId(id)]==='boolean')$(toggleId(id)).checked=d[toggleId(id)]});syncSettingsUi();updatePromoPanel();syncUiTheme()}
function setBatchStatus(text,type=''){$('batchStatus').textContent=text;$('batchStatus').className='batch-status'+(type?' '+type:'')}
function markBatchDirty(){if(state.workMode!=='batch'||state.batchBusy)return;state.batchDirty=true;setBatchStatus('Есть несохранённые изменения','dirty')}
function save(){if(state.workMode==='batch'){markBatchDirty();return}localStorage.setItem(platform.storageKey,JSON.stringify(collectEditorData()))}
let batchDbPromise=null,batchStorageFallback=false;const batchMemory=new Map();
function openBatchDb(){if(batchStorageFallback)return Promise.resolve(null);if(batchDbPromise)return batchDbPromise;batchDbPromise=new Promise(resolve=>{try{const request=indexedDB.open('titan-auto-batch',1);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains('vehicles'))request.result.createObjectStore('vehicles',{keyPath:'id'})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>{batchStorageFallback=true;console.warn('IndexedDB недоступен, используется память вкладки');resolve(null)}}catch(e){batchStorageFallback=true;console.warn(e);resolve(null)}});return batchDbPromise}
async function batchPut(record){const db=await openBatchDb();if(!db){batchMemory.set(record.id,record);return}await new Promise((resolve,reject)=>{const req=db.transaction('vehicles','readwrite').objectStore('vehicles').put(record);req.onsuccess=()=>resolve();req.onerror=()=>reject(req.error)})}
async function batchGet(id){const db=await openBatchDb();if(!db)return batchMemory.get(id)||null;return new Promise((resolve,reject)=>{const req=db.transaction('vehicles').objectStore('vehicles').get(id);req.onsuccess=()=>resolve(req.result||null);req.onerror=()=>reject(req.error)})}
async function batchAll(){const db=await openBatchDb();if(!db)return[...batchMemory.values()];return new Promise((resolve,reject)=>{const req=db.transaction('vehicles').objectStore('vehicles').getAll();req.onsuccess=()=>resolve(req.result||[]);req.onerror=()=>reject(req.error)})}
async function batchDelete(id){const db=await openBatchDb();if(!db){batchMemory.delete(id);return}await new Promise((resolve,reject)=>{const req=db.transaction('vehicles','readwrite').objectStore('vehicles').delete(id);req.onsuccess=()=>resolve();req.onerror=()=>reject(req.error)})}
function batchId(){return crypto.randomUUID?.()||`auto-${Date.now()}-${Math.random().toString(16).slice(2)}`}
function photoData(p){return{file:p.file,sourceName:p.sourceName,sourceSize:p.sourceSize,optimizedSize:p.optimizedSize,width:p.width,height:p.height,collage:{...p.collage},single:{...p.single}}}
function currentBatchRecord(id=state.batchActiveId||batchId(),createdAt=Date.now()){return{id,createdAt,updatedAt:Date.now(),editor:collectEditorData(),photos:state.photos.map(photoData)}}
async function hydratePhotos(items=[]){const loaded=[];for(const item of items){const file=item.file instanceof File?item.file:new File([item.file],item.sourceName||'photo.jpg',{type:item.file?.type||'image/jpeg'}),url=URL.createObjectURL(file),img=await loadImage(url);loaded.push({file,url,img,sourceName:item.sourceName||file.name,sourceSize:Number(item.sourceSize)||file.size,optimizedSize:Number(item.optimizedSize)||file.size,width:Number(item.width)||img.width,height:Number(item.height)||img.height,collage:{x:Number(item.collage?.x)||0,y:Number(item.collage?.y)||0,zoom:Number(item.collage?.zoom)||1},single:{x:Number(item.single?.x)||0,y:Number(item.single?.y)||0,zoom:Number(item.single?.zoom)||1}})}return loaded}
function releaseCurrentPhotos(){state.photos.forEach(p=>URL.revokeObjectURL(p.url));state.photos=[]}
async function loadBatchRecord(record,makeActive=true){if(!record)return;releaseCurrentPhotos();state.photos=await hydratePhotos(record.photos);applyEditorData(record.editor);state.page=0;state.slot=0;state.projectId=null;state.projectDir=null;if(makeActive){state.batchActiveId=record.id;localStorage.setItem('titan-batch-active',record.id)}state.batchDirty=false;renderThumbs();draw()}
function batchEditorForNewVehicle(){const d={...collectEditorData()};['sourceText','model','year','mileage','price','salePrice','features'].forEach(id=>d[id]='');d.soldMode=false;d.soldDays='10';d.textPreset='default';d.arrivalLabel='НОВОЕ ПОСТУПЛЕНИЕ';d.cta=textPresets.default.cta;return d}
async function renderBatchVehicles(){const records=(await batchAll()).sort((a,b)=>a.createdAt-b.createdAt),list=$('batchVehicleList');list.innerHTML='';records.forEach((record,index)=>{const card=document.createElement('div'),main=document.createElement('button'),remove=document.createElement('button'),title=[record.editor?.model||`Автомобиль ${index+1}`,record.editor?.year].filter(Boolean).join(' ');card.className='batch-vehicle'+(record.id===state.batchActiveId?' active':'');main.type='button';main.className='batch-vehicle-main';main.innerHTML=`<span class="batch-vehicle-title">${title.replace(/[<>&]/g,s=>({'<':'&lt;','>':'&gt;','&':'&amp;'}[s]))}</span><span class="batch-vehicle-meta">${record.photos?.length||0} фото${record.editor?.soldMode?' · ПРОДАНО':''}${record.id===state.batchActiveId?' · редактируется':''}</span>`;main.onclick=()=>switchBatchVehicle(record.id);remove.type='button';remove.className='batch-vehicle-remove';remove.textContent='×';remove.title='Удалить из подборки';remove.onclick=()=>removeBatchVehicle(record.id);card.append(main,remove);list.append(card)});$('exportBatchBtn').disabled=!records.length||state.batchBusy;setBatchStatus(state.batchDirty?'Есть несохранённые изменения':records.length?`${records.length} авто в подборке · данные хранятся локально`:'Подборка пока пуста',state.batchDirty?'dirty':'')}
function setBatchBusy(busy,text=''){state.batchBusy=busy;['singleModeBtn','batchModeBtn','newBatchVehicleBtn','saveBatchVehicleBtn','exportBatchBtn'].forEach(id=>$(id).disabled=busy);if(text)setBatchStatus(text,'busy')}
async function saveActiveBatchVehicle(showToast=false){if(state.workMode!=='batch'||!state.batchActiveId)return;const previous=await batchGet(state.batchActiveId),record=currentBatchRecord(state.batchActiveId,previous?.createdAt||Date.now());await batchPut(record);state.batchDirty=false;await renderBatchVehicles();if(showToast)toast('Автомобиль сохранён в подборке')}
async function switchBatchVehicle(id){if(state.batchBusy||id===state.batchActiveId)return;try{setBatchBusy(true,'Сохраняю текущий автомобиль…');await saveActiveBatchVehicle();const record=await batchGet(id);setBatchStatus('Открываю автомобиль…','busy');await loadBatchRecord(record);await renderBatchVehicles()}catch(e){toast('Не удалось переключить автомобиль: '+e.message)}finally{setBatchBusy(false)}}
async function newBatchVehicle(){if(state.batchBusy)return;try{setBatchBusy(true,'Сохраняю текущий автомобиль…');await saveActiveBatchVehicle();const editor=batchEditorForNewVehicle(),record={id:batchId(),createdAt:Date.now(),updatedAt:Date.now(),editor,photos:[]};await batchPut(record);await loadBatchRecord(record);await renderBatchVehicles();toast('Добавлен новый автомобиль')}catch(e){toast('Не удалось добавить автомобиль: '+e.message)}finally{setBatchBusy(false)}}
async function removeBatchVehicle(id){if(state.batchBusy||!confirm('Удалить этот автомобиль из пакетной подборки?'))return;try{setBatchBusy(true,'Удаляю автомобиль…');await batchDelete(id);const records=(await batchAll()).sort((a,b)=>a.createdAt-b.createdAt);if(id===state.batchActiveId){if(records.length)await loadBatchRecord(records[0]);else{const record={id:batchId(),createdAt:Date.now(),updatedAt:Date.now(),editor:batchEditorForNewVehicle(),photos:[]};await batchPut(record);await loadBatchRecord(record)}}await renderBatchVehicles()}catch(e){toast('Не удалось удалить автомобиль: '+e.message)}finally{setBatchBusy(false)}}
function syncWorkflowUi(){const batch=state.workMode==='batch';$('singleModeBtn').classList.toggle('active',!batch);$('batchModeBtn').classList.toggle('active',batch);$('batchManager').hidden=!batch;$('downloadBtn').textContent=batch?'Сохранить сторис текущего':'Сохранить все сторис'}
async function setWorkMode(mode){if(state.batchBusy||mode===state.workMode)return;try{setBatchBusy(true,mode==='batch'?'Открываю пакетный режим…':'Сохраняю подборку…');if(mode==='batch'){state.singleDraft={editor:collectEditorData(),photos:state.photos.map(photoData)};state.workMode='batch';syncWorkflowUi();const records=(await batchAll()).sort((a,b)=>a.createdAt-b.createdAt);if(records.length){const preferredId=localStorage.getItem('titan-batch-active'),preferred=preferredId?await batchGet(preferredId):null;await loadBatchRecord(preferred||records[0])}else{const record=currentBatchRecord(batchId(),Date.now());state.batchActiveId=record.id;await batchPut(record);state.batchDirty=false}await renderBatchVehicles()}else{await saveActiveBatchVehicle();state.workMode='single';syncWorkflowUi();if(state.singleDraft){releaseCurrentPhotos();state.photos=await hydratePhotos(state.singleDraft.photos);applyEditorData(state.singleDraft.editor);state.page=0;state.slot=0;renderThumbs();draw()}setBatchStatus('Подборка сохранена локально')}}catch(e){console.error(e);toast('Не удалось переключить режим: '+e.message)}finally{setBatchBusy(false)}}
async function exportBatchMains(){if(state.batchBusy)return;const activeId=state.batchActiveId;try{setBatchBusy(true,'Сохраняю текущий автомобиль…');await saveActiveBatchVehicle();const records=(await batchAll()).sort((a,b)=>a.createdAt-b.createdAt),chunkSize=12,totalParts=Math.ceil(records.length/chunkSize);state.exporting=true;for(let start=0;start<records.length;start+=chunkSize){const entries=[],part=Math.floor(start/chunkSize)+1,end=Math.min(records.length,start+chunkSize);for(let i=start;i<end;i++){setBatchStatus(`Создаю главные сторис: ${i+1} / ${records.length}`,'busy');await loadBatchRecord(records[i],false);state.page=0;draw();const blob=await canvasBlob(),name=`${String(i+1).padStart(2,'0')} — ${safeName([records[i].editor?.model||'Автомобиль',records[i].editor?.year].filter(Boolean).join(' '))}.png`;entries.push({name,data:new Uint8Array(await blob.arrayBuffer())});await nextFrame()}const suffix=totalParts>1?` — часть ${part} из ${totalParts}`:'';triggerDownload(zipFiles(entries),`ТИТАН АВТО — главные сторис${suffix} — ${dateStamp()}.zip`);await nextFrame()}toast(`Готово: ${records.length} главных сторис${totalParts>1?` · ${totalParts} ZIP`:''}`)}catch(e){toast('Не удалось собрать подборку: '+e.message)}finally{state.exporting=false;const active=await batchGet(activeId);if(active)await loadBatchRecord(active);await renderBatchVehicles();setBatchBusy(false)}}
function setupBatchUi(){$('singleModeBtn').onclick=()=>setWorkMode('single');$('batchModeBtn').onclick=()=>setWorkMode('batch');$('newBatchVehicleBtn').onclick=newBatchVehicle;$('saveBatchVehicleBtn').onclick=()=>saveActiveBatchVehicle(true);$('exportBatchBtn').onclick=exportBatchMains;syncWorkflowUi()}
function restore(){try{const d=JSON.parse(localStorage.getItem(platform.storageKey)),legacy=!!d&&!d.purchaseOption;if(d){applyEditorData(d);if(d.textPreset==null)$('textPreset').value='custom';if(d.soldTextPreset==null)$('soldTextPreset').value='custom'}if(!$('location').value||$('location').value==='Самара')$('location').value='Самара · Мирная, 3, корпус 1';if(!$('phone').value)$('phone').value='+7 927 265 17 77';if(!$('purchaseOption').value)$('purchaseOption').value='Наличные · кредит · обмен с вашей/нашей доплатой';if(!$('cta').value||(legacy&&$('cta').value==='Пишите, звоните за подробностями'))$('cta').value=DEFAULT_CTA}catch{$('phone').value='+7 927 265 17 77';$('purchaseOption').value='Наличные · кредит · обмен с вашей/нашей доплатой';$('cta').value=DEFAULT_CTA}syncUiTheme()}

function platformPrice(value){return value?Number(value).toLocaleString('ru-RU')+' ₽':''}
function platformVehicleData(vehicle,company){
  const specs=[vehicle.engine_volume&&`Двигатель ${vehicle.engine_volume} л`,vehicle.engine_power&&`${vehicle.engine_power} л.с.`,vehicle.fuel_type,vehicle.transmission,vehicle.drive_type,vehicle.body_type,vehicle.color,vehicle.owners_count&&`Владельцев: ${vehicle.owners_count}`].filter(Boolean);
  return{model:[vehicle.brand,vehicle.model,vehicle.generation].filter(Boolean).join(' ').toUpperCase(),year:String(vehicle.year||''),mileage:vehicle.mileage?Number(vehicle.mileage).toLocaleString('ru-RU')+' км':'',price:platformPrice(vehicle.sale_price||vehicle.market_price||vehicle.seller_price),salePrice:'',features:specs.slice(0,6).join('\n').toUpperCase(),location:vehicle.location||company.address||'Самара · Мирная, 3, корпус 1',phone:company.phone||'+7 927 265 17 77',sourceText:vehicle.description||vehicle.notes||'',soldMode:vehicle.status==='sold'};
}
function loadPlatformVehicle(vehicle,company={}){
  platform.vehicle=vehicle;platform.company=company;platform.storageKey=`titan-story-data:${vehicle.vehicle_id}`;state.projectId=vehicle.vehicle_id;
  const saved=localStorage.getItem(platform.storageKey);
  if(saved){try{applyEditorData(JSON.parse(saved))}catch(e){console.warn(e)}}else applyEditorData(platformVehicleData(vehicle,company));
  save();renderThumbs();draw();$('cloudSaveBtn').hidden=false;$('cloudSaveBtn').textContent=`Сохранить в TITAN AUTO · ${vehicle.vehicle_id}`;
}
function blobToDataUrl(blob){return new Promise((resolve,reject)=>{const reader=new FileReader;reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(reader.error||new Error('Не удалось прочитать файл'));reader.readAsDataURL(blob)})}
function platformUpload(file,description){
  const requestId=`story-${Date.now()}-${++platform.seq}`;
  return new Promise((resolve,reject)=>{platform.pending.set(requestId,{resolve,reject});parent.postMessage({type:'TITAN_STORY_UPLOAD',requestId,vehicleId:platform.vehicle.vehicle_id,file,description},location.origin)});
}
async function saveToPlatform(){
  if(!platform.vehicle||state.archiveBusy)return;
  const button=$('cloudSaveBtn'),oldPage=state.page,title=vehicleTitle();button.disabled=true;state.archiveBusy=true;
  try{
    const storyFiles=Array.from({length:pages()},(_,i)=>storyArchiveName(i)),photoFiles=state.photos.map((p,i)=>`${String(i+1).padStart(2,'0')} — Исходное фото${photoExtension(p.file)}`);
    const project={schema:'titan-auto-story-project',version:3,id:platform.vehicle.vehicle_id,vehicle:title,vehicle_id:platform.vehicle.vehicle_id,savedAt:new Date().toISOString(),editor:collectEditorData(),photos:state.photos.map((p,i)=>({name:p.file?.name||photoFiles[i],type:p.file?.type||'image/jpeg',fileName:photoFiles[i],sourceName:p.sourceName,sourceSize:p.sourceSize,optimizedSize:p.optimizedSize,width:p.width,height:p.height,collage:{...p.collage},single:{...p.single}})),storyFiles};
    const json=new Blob([JSON.stringify(project,null,2)],{type:'application/json'});button.textContent='Сохраняю проект…';await platformUpload({filename:'project.json',mimeType:'application/json',dataUrl:await blobToDataUrl(json)},`Проект редактора сторис · ${title}`);
    for(let i=0;i<state.photos.length;i++){button.textContent=`Исходники ${i+1} / ${state.photos.length}`;await platformUpload({filename:photoFiles[i],mimeType:state.photos[i].file.type||'image/jpeg',dataUrl:await blobToDataUrl(state.photos[i].file)},`Исходное фото для сторис · ${title}`)}
    state.exporting=true;
    for(let i=0;i<pages();i++){button.textContent=`Сторис ${i+1} / ${pages()}`;state.page=i;draw();const blob=await canvasBlob();await platformUpload({filename:storyFiles[i],mimeType:'image/png',dataUrl:await blobToDataUrl(blob)},`Готовая сторис ${i+1} из ${pages()} · ${title}`)}
    toast(`В Google Drive сохранено: ${storyFiles.length} сторис, ${photoFiles.length} фото и проект`);
  }catch(e){toast('Не удалось сохранить в TITAN AUTO: '+e.message)}finally{state.exporting=false;state.archiveBusy=false;state.page=oldPage;draw();button.disabled=false;button.textContent=`Сохранить в TITAN AUTO · ${platform.vehicle.vehicle_id}`}
}
addEventListener('message',event=>{if(event.origin!==location.origin)return;const message=event.data||{};if(message.type==='TITAN_STORIES_LOAD'&&message.vehicle)loadPlatformVehicle(message.vehicle,message.company||{});if(message.type==='TITAN_STORY_UPLOAD_RESULT'){const pending=platform.pending.get(message.requestId);if(!pending)return;platform.pending.delete(message.requestId);message.ok?pending.resolve(message.file):pending.reject(new Error(message.error||'Ошибка загрузки'))}});

function safeName(value,fallback='Автомобиль'){return(value||fallback).replace(/[<>:"/\\|?*\x00-\x1F]/g,' ').replace(/\s+/g,' ').replace(/[. ]+$/g,'').trim().slice(0,110)||fallback}
function dateStamp(){const d=new Date(),p=n=>String(n).padStart(2,'0');return`${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())} ${p(d.getHours())}-${p(d.getMinutes())}`}
function vehicleTitle(){return safeName([$('model').value.trim()||'Автомобиль',$('year').value.trim()].filter(Boolean).join(' '))}
function ensureProjectId(){if(!state.projectId)state.projectId=safeName(`${vehicleTitle()} — ${dateStamp()}`);return state.projectId}
function storyArchiveName(page){const title=vehicleTitle(),num=String(page+1).padStart(2,'0');if(page===0)return`01 — Главная — ${title}.png`;if(isPromoPage(page))return`99 — Финальная — ${title}.png`;return`${num} — Фото ${page+1} — ${title}.png`}
function photoExtension(file){const ext=file?.name?.match(/\.[a-z0-9]{2,5}$/i)?.[0];if(ext)return ext.toLowerCase();return({'image/jpeg':'.jpg','image/png':'.png','image/webp':'.webp','image/heic':'.heic','image/avif':'.avif'})[file?.type]||'.jpg'}
function photoArchiveName(photo,index){return`${String(index+1).padStart(2,'0')} — Оптимизированное фото${photoExtension(photo.file)}`}
function fileToDataUrl(file){return new Promise((resolve,reject)=>{const reader=new FileReader;reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(reader.error||new Error('Не удалось прочитать фото'));reader.readAsDataURL(file)})}
function dataUrlToBlob(value){const comma=value.indexOf(',');if(comma<0)throw new Error('Повреждённые данные фото');const meta=value.slice(0,comma),payload=value.slice(comma+1),mime=meta.match(/^data:([^;,]+)/)?.[1]||'application/octet-stream',binary=/;base64/i.test(meta)?atob(payload):decodeURIComponent(payload),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return new Blob([bytes],{type:mime})}
async function buildProjectData(){const photos=[];for(let i=0;i<state.photos.length;i++){const p=state.photos[i];setArchiveStatus(`Готовлю фото для JSON: ${i+1} / ${state.photos.length}`,'busy');await nextFrame();photos.push({name:p.file?.name||photoArchiveName(p,i),type:p.file?.type||'image/jpeg',fileName:photoArchiveName(p,i),dataUrl:await fileToDataUrl(p.file),sourceName:p.sourceName||p.file?.name,sourceSize:p.sourceSize||p.file?.size,optimizedSize:p.optimizedSize||p.file?.size,width:p.width||p.img?.width,height:p.height||p.img?.height,collage:{...p.collage},single:{...p.single}})}return{schema:'titan-auto-story-project',version:2,id:ensureProjectId(),vehicle:vehicleTitle(),savedAt:new Date().toISOString(),editor:collectEditorData(),photos}}
function setArchiveStatus(text,type=''){$('archiveStatus').textContent=text;$('archiveStatus').className='archive-status'+(type?' '+type:'')}
function setArchiveBusy(busy){state.archiveBusy=busy;['connectFolderBtn','saveArchiveBtn','openProjectFolderBtn','downloadProjectBtn'].forEach(id=>$(id).disabled=busy)}
async function writeDirectoryFile(dir,name,data){const handle=await dir.getFileHandle(name,{create:true}),writer=await handle.createWritable();await writer.write(data);await writer.close()}
async function connectArchiveFolder(){if(!window.showDirectoryPicker){setArchiveStatus('В этом браузере нет доступа к папкам. Откройте index.html в Chrome или Edge.','error');return null}try{const dir=await window.showDirectoryPicker({id:'titan-auto-ready-stories',mode:'readwrite'});state.archiveRoot=dir;state.projectDir=null;setArchiveStatus(`Подключена папка: ${dir.name}`,'connected');return dir}catch(e){if(e.name!=='AbortError')setArchiveStatus('Не удалось открыть папку: '+e.message,'error');return null}}
async function saveArchive(){if(state.archiveBusy)return;let projectDir=state.projectDir;if(!projectDir){const root=state.archiveRoot||await connectArchiveFolder();if(!root)return;const cars=await root.getDirectoryHandle('! Серии сторис одного авто',{create:true});projectDir=await cars.getDirectoryHandle(ensureProjectId(),{create:true});state.projectDir=projectDir}const oldPage=state.page;try{setArchiveBusy(true);setArchiveStatus('Готовлю JSON и исходники…','busy');const project=await buildProjectData(),photosDir=await projectDir.getDirectoryHandle('Фото',{create:true}),storiesDir=await projectDir.getDirectoryHandle('Сторис',{create:true});for(let i=0;i<state.photos.length;i++){setArchiveStatus(`Сохраняю исходники: ${i+1} / ${state.photos.length}`,'busy');await writeDirectoryFile(photosDir,project.photos[i].fileName,state.photos[i].file)}let mainBlob=null;state.exporting=true;for(let i=0;i<pages();i++){setArchiveStatus(`Создаю PNG: ${i+1} / ${pages()}`,'busy');state.page=i;draw();const blob=await canvasBlob();if(i===0)mainBlob=blob;await writeDirectoryFile(storiesDir,storyArchiveName(i),blob)}project.storyFiles=Array.from({length:pages()},(_,i)=>storyArchiveName(i));await writeDirectoryFile(projectDir,'project.json',new Blob([JSON.stringify(project,null,2)],{type:'application/json'}));if(state.archiveRoot&&mainBlob){const mains=await state.archiveRoot.getDirectoryHandle('! Главные сторис',{create:true});await writeDirectoryFile(mains,`${ensureProjectId()} — Главная.png`,mainBlob)}setArchiveStatus(`Сохранено: ${projectDir.name} · ${pages()} PNG · ${state.photos.length} фото`,'connected');toast('Проект, PNG и исходники сохранены')}catch(e){setArchiveStatus('Ошибка сохранения: '+e.message,'error')}finally{state.exporting=false;state.page=oldPage;setArchiveBusy(false);draw()}}
async function photoFromProject(item,dir){let file;if(item.dataUrl){const blob=dataUrlToBlob(item.dataUrl);file=new File([blob],item.name||item.fileName||'фото.jpg',{type:item.type||blob.type||'image/jpeg'})}else if(dir&&item.fileName){const photosDir=await dir.getDirectoryHandle('Фото'),handle=await photosDir.getFileHandle(item.fileName);file=await handle.getFile()}else throw new Error('В JSON нет встроенного фото');const url=URL.createObjectURL(file),img=await loadImage(url);return{file,url,img,sourceName:item.sourceName||item.name,sourceSize:Number(item.sourceSize)||file.size,optimizedSize:Number(item.optimizedSize)||file.size,width:Number(item.width)||img.width,height:Number(item.height)||img.height,collage:{x:Number(item.collage?.x)||0,y:Number(item.collage?.y)||0,zoom:Number(item.collage?.zoom)||1},single:{x:Number(item.single?.x)||0,y:Number(item.single?.y)||0,zoom:Number(item.single?.zoom)||1}}}
async function loadProjectData(project,dir=null){if(project?.schema!=='titan-auto-story-project'||!project.editor||!Array.isArray(project.photos))throw new Error('Это не project.json генератора');setArchiveBusy(true);setArchiveStatus('Восстанавливаю фото и настройки…','busy');try{const loaded=[];for(let i=0;i<project.photos.length;i++){setArchiveStatus(`Открываю фото: ${i+1} / ${project.photos.length}`,'busy');loaded.push(await photoFromProject(project.photos[i],dir))}state.photos.forEach(p=>URL.revokeObjectURL(p.url));state.photos=loaded;state.projectId=safeName(project.id||dir?.name||`${project.vehicle||'Автомобиль'} — ${dateStamp()}`);state.projectDir=dir;state.page=0;state.slot=0;applyEditorData(project.editor);save();renderThumbs();draw();setArchiveStatus(`Открыт проект: ${project.vehicle||state.projectId} · ${loaded.length} фото`,'connected');toast('Проект восстановлен')}finally{setArchiveBusy(false)}}
async function openProjectFolder(){if(!window.showDirectoryPicker){setArchiveStatus('Открытие папок доступно в Chrome или Edge.','error');return}try{const dir=await window.showDirectoryPicker({id:'titan-auto-project',mode:'readwrite'}),handle=await dir.getFileHandle('project.json'),project=JSON.parse(await(await handle.getFile()).text());await loadProjectData(project,dir)}catch(e){if(e.name!=='AbortError')setArchiveStatus('Не удалось открыть проект: '+e.message,'error')}}
async function downloadProjectJson(){try{setArchiveBusy(true);setArchiveStatus('Готовлю самодостаточный JSON…','busy');const project=await buildProjectData(),blob=new Blob([JSON.stringify(project,null,2)],{type:'application/json'});triggerDownload(blob,`${ensureProjectId()} — project.json`);setArchiveStatus('Самодостаточный JSON с фотографиями скачан','connected')}catch(e){setArchiveStatus('Не удалось создать JSON: '+e.message,'error')}finally{setArchiveBusy(false)}}
async function importProjectFile(file){try{const project=JSON.parse(await file.text());await loadProjectData(project);setArchiveStatus(`Открыт JSON: ${file.name}`,'connected')}catch(e){setArchiveStatus('Не удалось открыть JSON: '+e.message,'error')}}
function syncUiTheme(){document.documentElement.style.setProperty('--red',$('brandColor').value);document.documentElement.style.setProperty('--red2',$('accentColor').value)}
function applyPalette(){const preset=palettes[$('palettePreset').value];if(preset){[$('brandColor').value,$('accentColor').value,$('backgroundColor').value]=preset}syncUiTheme();save();draw()}
function applyTextPreset(){const preset=textPresets[$('textPreset').value];if(preset)Object.entries(preset).forEach(([id,value])=>$(id).value=value);save();draw()}
function applySoldTextPreset(){const preset=soldTextPresets[$('soldTextPreset').value];if(preset)Object.entries(preset).forEach(([id,value])=>$(id).value=value);save();draw()}
function toggleSoldMode(){const controls=document.querySelector('.controls'),desktop=matchMedia('(min-width:901px)').matches,scrollTop=controls?.scrollTop||0;syncSettingsUi();if(desktop&&controls){const reset=()=>{controls.scrollTop=scrollTop;window.scrollTo(0,0);document.documentElement.scrollTop=0;document.body.scrollTop=0};reset();requestAnimationFrame(reset)}save();draw();requestAnimationFrame(draw);toast($('soldMode').checked?'Режим «Продано» включён':'Обычная сторис восстановлена')}
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2200)}
fields.forEach(id=>$(id).addEventListener('input',()=>{if(id==='cta')$('textPreset').value='custom';if(/^sold/.test(id)&&id!=='soldDays')$('soldTextPreset').value='custom';save();draw()}));settingFields.filter(id=>!['palettePreset','textPreset','soldTextPreset','brandColor','accentColor','backgroundColor','logoCaption','arrivalLabel'].includes(id)).forEach(id=>$(id).addEventListener('change',()=>{save();renderThumbs();draw()}));$('logoCaption').addEventListener('input',()=>{save();draw()});$('arrivalLabel').addEventListener('input',()=>{$('textPreset').value='custom';save();draw()});checkboxFields.filter(id=>id!=='soldMode').forEach(id=>$(id).addEventListener('change',()=>{syncSettingsUi();save();draw()}));$('soldMode').addEventListener('change',toggleSoldMode);$('palettePreset').addEventListener('change',applyPalette);$('textPreset').addEventListener('change',applyTextPreset);$('soldTextPreset').addEventListener('change',applySoldTextPreset);['brandColor','accentColor','backgroundColor'].forEach(id=>$(id).addEventListener('input',()=>{$('palettePreset').value='custom';syncUiTheme();save();draw()}));$('parseBtn').onclick=parseAd;$('photos').onchange=e=>addPhotos(e.target.files);$('prevBtn').onclick=()=>{state.page=Math.max(0,state.page-1);draw()};$('nextBtn').onclick=()=>{state.page=Math.min(pages()-1,state.page+1);draw()};$('downloadBtn').onclick=downloadAll;$('downloadBtnBottom').onclick=()=>downloadPage();$('cloudSaveBtn').onclick=saveToPlatform;$('connectFolderBtn').onclick=connectArchiveFolder;$('saveArchiveBtn').onclick=saveArchive;$('openProjectFolderBtn').onclick=openProjectFolder;$('downloadProjectBtn').onclick=downloadProjectJson;$('projectFile').onchange=e=>{const file=e.target.files?.[0];if(file)importProjectFile(file);e.target.value=''};$('resetBtn').onclick=()=>{if(confirm('Очистить все поля и фотографии?')){localStorage.removeItem(platform.storageKey);location.reload()}};
function beginPinch(){const points=[...state.pointers.values()];if(points.length<2||!state.drag)return;const [a,b]=points,midX=(a.x+b.x)/2,midY=(a.y+b.y)/2;state.pinch={distance:Math.hypot(a.x-b.x,a.y-b.y),midX,midY,zoom:state.drag.t.zoom,ox:state.drag.t.x,oy:state.drag.t.y,t:state.drag.t}}
function endPointer(e){state.pointers.delete(e.pointerId);state.pinch=null;const remaining=[...state.pointers.values()][0];if(remaining&&state.drag)state.drag={x:remaining.x,y:remaining.y,ox:state.drag.t.x,oy:state.drag.t.y,t:state.drag.t};else state.drag=null}
canvas.addEventListener('pointerdown',e=>{const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*1080/r.width,y=(e.clientY-r.top)*1920/r.height,t=state.drag?.t||transformAt(x,y);if(!t)return;e.preventDefault();canvas.setPointerCapture(e.pointerId);state.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(!state.drag)state.drag={x:e.clientX,y:e.clientY,ox:t.x,oy:t.y,t};if(state.pointers.size===2)beginPinch()});
canvas.addEventListener('pointermove',e=>{if(!state.pointers.has(e.pointerId)||!state.drag)return;state.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});const s=1080/canvas.clientWidth;if(state.pointers.size>=2){if(!state.pinch)beginPinch();const [a,b]=[...state.pointers.values()],distance=Math.hypot(a.x-b.x,a.y-b.y),midX=(a.x+b.x)/2,midY=(a.y+b.y)/2,p=state.pinch;if(!p)return;p.t.zoom=Math.max(1,Math.min(3,p.zoom*distance/Math.max(1,p.distance)));p.t.x=p.ox+(midX-p.midX)*s;p.t.y=p.oy+(midY-p.midY)*s}else{state.drag.t.x=state.drag.ox+(e.clientX-state.drag.x)*s;state.drag.t.y=state.drag.oy+(e.clientY-state.drag.y)*s}draw()});
canvas.addEventListener('pointerup',endPointer);canvas.addEventListener('pointercancel',endPointer);canvas.addEventListener('lostpointercapture',endPointer);canvas.addEventListener('wheel',e=>{e.preventDefault();if(isPromoPage())return;const t=state.page>0?state.photos[state.page]?.single:state.photos[state.slot]?.collage;if(!t)return;t.zoom=Math.max(1,Math.min(3,t.zoom+(e.deltaY<0?.06:-.06)));draw()},{passive:false});
$('promoStyle').addEventListener('change',updatePromoPanel);
init();
