import { useMemo, useRef, useState } from 'react'
import { DOCUMENTS, EMPTY_DEAL } from './data'
import { createPackage, printPackage, validateDeal } from './docx'
import { exportDeal, importDeal, saveDealFile, saveDraft } from './storage'
import type { DealData, ScanAttachment } from './types'
import './review.css'

const STEPS=['Пакет документов','Условия сделки','Финальная проверка']
const clone=<T,>(x:T):T=>structuredClone(x)
const Field=({label,value,onChange,type='text',required=false}:{label:string;value:string;onChange:(v:string)=>void;type?:string;required?:boolean})=><label className="field"><span>{label}{required&&<b className="required"> *</b>}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)}/></label>
const TextArea=({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void})=><label className="field full"><span>{label}</span><textarea value={value} onChange={e=>onChange(e.target.value)}/></label>

export interface DealEditorProps{initialData?:DealData;initialScans?:ScanAttachment[];dealType?:string;templateFile?:File;templateName?:string;onBack?:()=>void;onPersist?:(data:DealData)=>Promise<void>|void;onEditSeller?:()=>void;onEditBuyer?:()=>void;onEditVehicle?:()=>void}
export default function App({initialData,initialScans=[],dealType,templateFile,templateName,onBack,onPersist,onEditSeller,onEditBuyer,onEditVehicle}:DealEditorProps){
  const [data,setData]=useState(()=>clone(initialData||EMPTY_DEAL)),[active,setActive]=useState(0),[done,setDone]=useState<number[]>([]),[scans]=useState(initialScans),[toast,setToast]=useState(''),[busy,setBusy]=useState(false)
  const importRef=useRef<HTMLInputElement>(null),errors=useMemo(()=>validateDeal(data),[data])
  const say=(s:string)=>{setToast(s);setTimeout(()=>setToast(''),2600)},change=(path:string,value:string)=>setData(prev=>{const next=clone(prev),keys=path.split('.');let target:any=next;keys.slice(0,-1).forEach(k=>target=target[k]);target[keys.at(-1)!]=value;return next})
  const next=()=>{const missing=active===0&&data.mode==='titan'&&!data.selectedDocuments.length?['не выбран ни один документ']:[!data.deal.contract_number&&'номер договора',!data.deal.contract_date&&'дата договора',!data.terms.price&&'цена автомобиля'].filter(Boolean) as string[];if(missing.length&&!confirm(`Не заполнено:\n\n• ${missing.join('\n• ')}\n\nВсё равно перейти дальше?`))return;setDone(x=>[...new Set([...x,active])]);setActive(x=>Math.min(2,x+1))}
  const toggleDoc=(id:string)=>setData(x=>({...x,selectedDocuments:x.selectedDocuments.includes(id)?x.selectedDocuments.filter(v=>v!==id):[...x.selectedDocuments,id]})),persist=async()=>{await saveDraft(data);await onPersist?.(data);say('Сделка сохранена')},confirmFinal=(action:string)=>!errors.length||confirm(`Перед ${action} не заполнено:\n\n• ${errors.join('\n• ')}\n\nВсё равно продолжить?`)
  const generate=async()=>{if(!confirmFinal('формированием'))return;setBusy(true);try{await createPackage(data,scans,templateFile);say('Пакет сформирован')}catch(e){say(e instanceof Error?e.message:'Ошибка формирования')}finally{setBusy(false)}},printAll=async()=>{if(!confirmFinal('печатью'))return;setBusy(true);try{await printPackage(data,scans,templateFile);say('Открыто окно печати')}catch(e){say(e instanceof Error?e.message:'Ошибка печати')}finally{setBusy(false)}}
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><img src="./brand/logo.png"/><div><strong>ТИТАН АВТО</strong><small>Конструктор документов</small></div></div><div className="progress-label">Текущая сделка</div><nav>{STEPS.map((s,i)=><button key={s} className={`nav-step ${active===i?'active':''} ${done.includes(i)?'done':''}`} onClick={()=>setActive(i)}><span>{done.includes(i)?'✓':i+1}</span>{s}</button>)}</nav>{onBack&&<button className="back-catalog" onClick={onBack}>← К списку сделок</button>}</aside><main><header className="hero"><div><div className="eyebrow">ДОКУМЕНТЫ</div><h1>Редактор сделки</h1></div><div className="deal-chip">Сделка <b>{data.deal.contract_number||'без номера'}</b></div></header><div className="mobile-progress">Шаг {active+1} из 3 · {STEPS[active]}</div><section className="workspace">
    {active===0&&<><Title n="01" title="Пакет документов" text="Участники и автомобиль уже определены в карточке сделки"/><div className="notice success"><b>{dealType==='private_sale'?'ДКП между физическими лицами':'С участием ТИТАН АВТО'}</b><span>Тип сделки задан при её создании и здесь повторно не выбирается.</span></div>{templateFile?<div className="notice success"><b>Подключён шаблон</b><span>{templateName||templateFile.name}</span></div>:data.mode==='titan'?<div className="document-list">{DOCUMENTS.map(doc=><label className="document-row" key={doc.id}><input type="checkbox" checked={data.selectedDocuments.includes(doc.id)} onChange={()=>toggleDoc(doc.id)}/><span className="doc-number">{doc.id}</span><span><b>{doc.name}</b><small>Официальный рабочий шаблон DOCX</small></span></label>)}</div>:<div className="notice success"><b>ДКП между физическими лицами</b><span>Формируется для покупателя, продавца и ГИБДД.</span></div>}<Next onClick={next}/></>}
    {active===1&&<><Title n="02" title="Условия сделки" text="Заполните только переменные условия и даты документов"/><div className="form-grid"><Field label="Номер договора" required value={data.deal.contract_number} onChange={v=>change('deal.contract_number',v)}/><Field label="Город" required value={data.deal.city} onChange={v=>change('deal.city',v)}/><Field label="Дата договора" required type="date" value={data.deal.contract_date} onChange={v=>change('deal.contract_date',v)}/><Field label="Цена автомобиля, ₽" required value={data.terms.price} onChange={v=>change('terms.price',v)}/>{data.mode==='titan'&&!templateFile&&<Field label="Вознаграждение ТИТАН АВТО, ₽" value={data.terms.commission} onChange={v=>change('terms.commission',v)}/>}</div>{!templateFile&&<><h3 className="subheading">Даты отдельных документов</h3><div className="date-grid">{DOCUMENTS.filter(x=>data.selectedDocuments.includes(x.id)&&x.id!=='01').map(doc=><Field key={doc.id} label={doc.name} type="date" value={data.documentDates[doc.id]||''} onChange={v=>change(`documentDates.${doc.id}`,v)}/>)}</div></>}{data.selectedDocuments.includes('04')&&<><h3 className="subheading">Изменение условий</h3><div className="form-grid"><Field label="Изменить пункт" value={data.terms.change_clause_number} onChange={v=>change('terms.change_clause_number',v)}/><TextArea label="Новая редакция" value={data.terms.change_clause_text} onChange={v=>change('terms.change_clause_text',v)}/><Field label="Исключить пункт" value={data.terms.exclude_clause_number} onChange={v=>change('terms.exclude_clause_number',v)}/><Field label="Дополнить пунктом" value={data.terms.add_clause_number} onChange={v=>change('terms.add_clause_number',v)}/><TextArea label="Текст дополнения" value={data.terms.add_clause_text} onChange={v=>change('terms.add_clause_text',v)}/></div></>}<Next onClick={next}/></>}
    {active===2&&<><Title n="03" title="Финальная проверка" text="Откройте карточки участников или автомобиля, если нужно внести исправления"/><div className={`notice ${errors.length?'warning':'success'}`}><b>{errors.length?'Нужно проверить':'Критических пропусков нет'}</b><span>{errors.length?errors.join(' · '):`${data.selectedDocuments.length||1} документов · ${scans.length} вложений`}</span></div><div className="review-grid"><Review label="Продавец — открыть карточку" value={data.seller.full_name||'Не заполнено'} onClick={onEditSeller}/>{data.buyer.full_name&&<Review label="Покупатель — открыть карточку" value={data.buyer.full_name} onClick={onEditBuyer}/>}<Review label="Автомобиль — открыть карточку" value={data.vehicle.vin?`${data.vehicle.make_model} · ${data.vehicle.vin}`:'Не заполнено'} onClick={onEditVehicle}/><Review label="Условия — вернуться" value={`№ ${data.deal.contract_number||'—'} от ${data.deal.contract_date}`} onClick={()=>setActive(1)}/></div>{scans.length>0&&<div className="scan-list">{scans.map(s=><span key={s.id}>{s.file.name}</span>)}</div>}<div className="deal-file-actions"><button className="secondary" onClick={()=>saveDealFile(data).then(say)}>Сохранить JSON сделки</button><button className="secondary" onClick={()=>importRef.current?.click()}>Загрузить JSON сделки</button></div><div className="final-actions"><button className="secondary" onClick={persist}>Сохранить сделку</button><button className="secondary" disabled={busy} onClick={printAll}>Печать всего комплекта</button><button className="primary" disabled={busy} onClick={generate}>{busy?'Формирование…':'Сформировать комплект'}</button></div></>}
  </section><footer><button onClick={()=>exportDeal(data)}>Скачать копию сделки</button><button onClick={()=>importRef.current?.click()}>Загрузить сделку</button><input ref={importRef} hidden type="file" accept=".json,.titan-deal.json" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{setData(await importDeal(f));setActive(0);setDone([]);say('Данные загружены')}catch(err){say(err instanceof Error?err.message:'Ошибка импорта')}finally{e.target.value=''}}}/></footer></main>{toast&&<div className="toast">{toast}</div>}</div>
}
const Title=({n,title,text}:{n:string;title:string;text:string})=><div className="section-title"><span>{n}</span><div><h2>{title}</h2><p>{text}</p></div></div>
const Next=({onClick}:{onClick:()=>void})=><div className="nextline"><button className="primary" onClick={onClick}>Далее →</button></div>
const Review=({label,value,onClick}:{label:string;value:string;onClick?:()=>void})=><button type="button" className="review" onClick={onClick}><span>✓</span><div><small>{label}</small><b>{value}</b></div></button>

