const STORAGE_KEY = 'titan-auto-pay-v1';
const MONTHS_RU = ['январь','февраль','март','апрель','май','июнь','июль','август','сентябрь','октябрь','ноябрь','декабрь'];
const MONTHS_SHORT = ['янв','фев','мар','апр','май','июн','июл','авг','сен','окт','ноя','дек'];
const DEFAULT_MANAGERS = ['Александр','Никита','Максим','Сергей','Дмитрий','Алексей'];
const defaults = {settings:{commissionFull:30,commissionPart:15,buyoutFull:20,buyoutPart:10,credit:12.5,defaultSalary:40000,ownManagerName:'Максим',managerNames:DEFAULT_MANAGERS},deals:[],months:{}};
let state = loadState();

function loadState(){try{const raw=JSON.parse(localStorage.getItem(STORAGE_KEY));return raw?{settings:{...defaults.settings,...raw.settings},deals:raw.deals||[],months:raw.months||{}}:structuredClone(defaults)}catch{return structuredClone(defaults)}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function money(value){return new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:0}).format(Number(value)||0)}
function signedMoney(value){const n=Number(value)||0;return `${n>0?'+ ':n<0?'− ':''}${money(Math.abs(n))}`}
function plainNumber(value){return new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(Number(value)||0)}
function percent(value,digits=1){return `${new Intl.NumberFormat('ru-RU',{maximumFractionDigits:digits}).format(Number(value)||0)}%`}
function num(id){return Number(document.getElementById(id).value)||0}
function currentMonth(){return new Date().toISOString().slice(0,7)}
function dateToMonth(date){return (date||new Date().toISOString().slice(0,10)).slice(0,7)}
function monthTitle(key){if(!key)return 'Без даты';const [y,m]=key.split('-').map(Number);return `${MONTHS_RU[m-1]} ${y}`}
function ownName(){return String(state.settings.ownManagerName||'Я').trim()||'Я'}
function cleanManagerName(name){const value=String(name||'').trim();return value.toLocaleLowerCase('ru-RU')==='я'?ownName():value}
function parseParticipants(value){const seen=new Set();return String(value||'').split(/[,;\n]+/).map(cleanManagerName).filter(name=>{const key=name.toLocaleLowerCase('ru-RU');if(!name||seen.has(key))return false;seen.add(key);return true})}
function managerCatalog(){
  const names=[...(Array.isArray(state.settings.managerNames)?state.settings.managerNames:DEFAULT_MANAGERS),ownName()];
  state.deals.forEach(d=>names.push(...parseParticipants(d.acceptedBy),...parseParticipants(d.soldBy),...parseParticipants(d.equalParticipants)));
  const seen=new Set();return names.map(cleanManagerName).filter(name=>{const key=name.toLocaleLowerCase('ru-RU');if(!name||seen.has(key))return false;seen.add(key);return true});
}
function sameManager(a,b){return cleanManagerName(a).localeCompare(cleanManagerName(b),'ru',{sensitivity:'accent'})===0}
function fullRate(deal){return deal.type==='buyout'?state.settings.buyoutFull:state.settings.commissionFull}
function legacyRate(deal){const s=state.settings;return deal.type==='buyout'?(deal.participation==='full'?s.buyoutFull:s.buyoutPart):(deal.participation==='full'?s.commissionFull:s.commissionPart)}
function addShare(map,name,kind,amount){if(!name||!amount)return;const key=name.toLocaleLowerCase('ru-RU');if(!map.has(key))map.set(key,{name,car:0,credit:0,total:0,buy:0,sale:0,equal:0,delta:0});const row=map.get(key);row[kind]+=amount;if(kind!=='credit')row.car+=amount}
function distribute(map,names,kind,pool){if(!names.length||!pool)return pool||0;const share=pool/names.length;names.forEach(name=>addShare(map,name,kind,share));return 0}
function stageCarShares(deal,carPool){const map=new Map(),buyers=parseParticipants(deal.acceptedBy),sellers=parseParticipants(deal.soldBy);distribute(map,buyers,'buy',carPool/2);distribute(map,sellers,'sale',carPool/2);return map}
function calcDeal(deal){
  if(!deal.allocationVersion){const rate=legacyRate(deal),car=(Number(deal.margin)||0)*rate/100,credit=(Number(deal.creditCommission)||0)*state.settings.credit/100,total=car+credit;return {rate,carPool:car,creditPool:credit,unallocated:0,ownTotal:total,allocatedTotal:total,legacy:true,distributions:[{name:ownName(),car,credit,total,buy:0,sale:0,equal:0,delta:0}]}}
  const rate=fullRate(deal),carPool=(Number(deal.margin)||0)*rate/100,creditPool=(Number(deal.creditCommission)||0)*state.settings.credit/100;
  const buyers=parseParticipants(deal.acceptedBy),sellers=parseParticipants(deal.soldBy),map=new Map();let unallocated=0;
  if(deal.allocationMode==='equal'){
    const equal=parseParticipants(deal.equalParticipants),recipients=equal.length?equal:[...new Set([...buyers,...sellers])];
    unallocated+=distribute(map,recipients,'equal',carPool);
    const fair=stageCarShares(deal,carPool),keys=new Set([...map.keys(),...fair.keys()]);
    keys.forEach(key=>{if(!map.has(key))map.set(key,{name:fair.get(key).name,car:0,credit:0,total:0,buy:0,sale:0,equal:0,delta:0});map.get(key).delta=map.get(key).car-(fair.get(key)?.car||0)});
  }else{unallocated+=distribute(map,buyers,'buy',carPool/2);unallocated+=distribute(map,sellers,'sale',carPool/2)}
  unallocated+=distribute(map,sellers,'credit',creditPool);
  const distributions=[...map.values()].map(row=>({...row,total:row.car+row.credit})).sort((a,b)=>b.total-a.total||a.name.localeCompare(b.name,'ru'));
  const own=distributions.find(row=>sameManager(row.name,ownName()));
  return {rate,carPool,creditPool,unallocated,ownTotal:own?.total||0,allocatedTotal:distributions.reduce((sum,row)=>sum+row.total,0),legacy:false,distributions};
}
function contributionWeights(deal){
  const map=new Map(),buyers=parseParticipants(deal.acceptedBy),sellers=parseParticipants(deal.soldBy);
  const add=(names,weight)=>names.forEach(name=>{const key=name.toLocaleLowerCase('ru-RU');if(!map.has(key))map.set(key,{name,weight:0});map.get(key).weight+=weight/names.length});
  if(buyers.length)add(buyers,.5);if(sellers.length)add(sellers,.5);
  const assigned=[...map.values()].reduce((sum,row)=>sum+row.weight,0);
  return {rows:[...map.values()],assigned};
}
function calcDirector(deal,dealCalc=calcDeal(deal)){
  const enabled=Boolean(deal.directorEnabled),margin=Number(deal.margin)||0,managerPay=deal.directorSubtractManagers===false?0:dealCalc.allocatedTotal,expenses=Number(deal.directorExpenses)||0;
  const beforeTax=margin-managerPay-expenses,taxRate=Number(deal.directorTaxRate??15)||0,tax=Math.max(0,beforeTax)*taxRate/100,afterTax=beforeTax-tax,selectedNet=deal.directorTaxEnabled===false?beforeTax:afterTax;
  const capital=Number(deal.directorCapital)||0,days=Math.max(1,Number(deal.directorDays)||1),periodReturn=capital?selectedNet/capital:0,annualSimple=periodReturn*365/days;
  const annualCompound=periodReturn>-1?Math.pow(1+periodReturn,365/days)-1:-1,bankRate=(Number(deal.bankRate??17)||0)/100,bankGross=capital*(Math.pow(1+bankRate/12,12*days/365)-1),bankTax=bankGross*.13,bankNet=bankGross-bankTax;
  const inflationRate=(Number(deal.inflationRate??5.2)||0)/100,inflationLoss=capital*(Math.pow(1+inflationRate,days/365)-1),realProfit=selectedNet-inflationLoss,advantage=selectedNet-bankNet;
  const weights=contributionWeights(deal),contributions=weights.rows.map(row=>({...row,value:selectedNet*row.weight,beforeTaxValue:beforeTax*row.weight,taxValue:(deal.directorTaxEnabled===false?0:tax)*row.weight,grossValue:margin*row.weight,bankValue:bankNet*row.weight}));
  return {enabled,margin,managerPay,expenses,beforeTax,taxRate,tax,afterTax,selectedNet,capital,days,periodReturn,annualSimple,annualCompound,bankGross,bankTax,bankNet,inflationLoss,realProfit,advantage,contributions,unassigned:selectedNet*(1-weights.assigned)};
}
function calcSettlement(deal,dealCalc=calcDeal(deal),director=calcDirector(deal,dealCalc)){
  const managerActual=deal.managerActualPayments||{},rows=[];
  rows.push({key:'owner',name:'Собственнику',due:Number(deal.ownerAmount)||0,actual:Number(deal.ownerPaidActual)||0,type:'owner'});
  dealCalc.distributions.filter(row=>row.total>0).forEach(row=>{const key=row.name.toLocaleLowerCase('ru-RU');rows.push({key,name:row.name,due:row.total,actual:Number(managerActual[key])||0,type:'manager',mine:sameManager(row.name,ownName())})});
  if(director.enabled)rows.push({key:'director',name:'Директору',due:director.selectedNet,actual:Number(deal.directorPaidActual)||0,type:'director'});
  const taxDue=director.enabled&&deal.directorTaxEnabled!==false?director.tax:0;if(taxDue||Number(deal.taxPaidActual))rows.push({key:'tax',name:'Налог / УСН',due:taxDue,actual:Number(deal.taxPaidActual)||0,type:'tax'});
  const expensesDue=director.enabled?director.expenses:0;if(expensesDue||Number(deal.expensesPaidActual))rows.push({key:'expenses',name:'Прочие расходы',due:expensesDue,actual:Number(deal.expensesPaidActual)||0,type:'expenses'});
  rows.forEach(row=>row.balance=row.due-row.actual);
  const buyerDue=Number(deal.salePrice)||0,buyerActual=Number(deal.buyerReceivedActual)||0,buyerBalance=buyerDue-buyerActual,totalDue=rows.reduce((sum,row)=>sum+row.due,0),totalActual=rows.reduce((sum,row)=>sum+row.actual,0),owed=rows.reduce((sum,row)=>sum+Math.max(0,row.balance),0),toReturn=rows.reduce((sum,row)=>sum+Math.max(0,-row.balance),0),cashBalance=buyerActual-totalActual;
  return {rows,buyerDue,buyerActual,buyerBalance,totalDue,totalActual,owed,toReturn,cashBalance,closed:Math.abs(buyerBalance)<.01&&owed<.01&&toReturn<.01};
}
function ensureMonth(key){if(!state.months[key])state.months[key]={salary:state.settings.defaultSalary,enabled:true,absorbed:true};return state.months[key]}
function calcMonth(key){const deals=state.deals.filter(d=>d.status==='sold'&&dateToMonth(d.date)===key),dealPay=deals.reduce((sum,d)=>sum+calcDeal(d).ownTotal,0),cfg=state.months[key]||{salary:state.settings.defaultSalary,enabled:key===currentMonth(),absorbed:true},salary=cfg.enabled?Number(cfg.salary)||0:0,total=cfg.absorbed?Math.max(dealPay,salary):dealPay+salary;return{deals,dealPay,salary,total,cfg,absorbedPart:cfg.absorbed?Math.min(dealPay,salary):0}}
function allMonthKeys(){const keys=new Set([...Object.keys(state.months),...state.deals.filter(d=>d.status==='sold').map(d=>dateToMonth(d.date)),currentMonth()]);return [...keys].sort().reverse()}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(text){const el=document.getElementById('toast');el.textContent=text;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2200)}
function plural(n,one,few,many){const x=Math.abs(n)%100,y=x%10;return x>10&&x<20?many:y>1&&y<5?few:y===1?one:many}

const titles={dashboard:['ФИНАНСЫ','Обзор'],deals:['УЧЁТ','Сделки'],months:['ВЫПЛАТЫ','По месяцам'],settings:['ПАРАМЕТРЫ','Настройки']};
function showView(view){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById(`${view}View`).classList.add('active');document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===view));document.getElementById('pageEyebrow').textContent=titles[view][0];document.getElementById('pageTitle').textContent=titles[view][1];document.querySelector('.sidebar').classList.remove('open');renderAll()}
document.querySelectorAll('.nav-item').forEach(n=>n.addEventListener('click',()=>showView(n.dataset.view)));
document.querySelectorAll('[data-go]').forEach(n=>n.addEventListener('click',()=>showView(n.dataset.go)));
document.getElementById('mobileMenu').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');

function fillMonthSelects(){const keys=allMonthKeys(),dash=document.getElementById('dashboardPeriod'),selected=dash.value||currentMonth();dash.innerHTML=keys.map(k=>`<option value="${k}">${monthTitle(k)}</option>`).join('');dash.value=keys.includes(selected)?selected:keys[0];const filter=document.getElementById('dealMonthFilter'),f=filter.value||'all';filter.innerHTML='<option value="all">Все месяцы</option>'+keys.map(k=>`<option value="${k}">${monthTitle(k)}</option>`).join('');filter.value=f}
function renderDashboard(){
  const key=document.getElementById('dashboardPeriod').value||currentMonth(),m=calcMonth(key),planned=state.deals.filter(d=>d.status==='planned'),pipeline=planned.reduce((sum,d)=>sum+calcDeal(d).ownTotal,0);
  document.getElementById('statPay').textContent=money(m.total);document.getElementById('statDeals').textContent=money(m.dealPay);document.getElementById('statDealsHint').textContent=`${m.deals.length} ${plural(m.deals.length,'реализовано','реализованы','реализовано')}`;
  document.getElementById('statSalary').textContent=money(m.salary);document.getElementById('statSalaryHint').textContent=!m.cfg.enabled?'Не учитывается':m.cfg.absorbed?'Поглощается заработком':'Прибавляется сверху';document.getElementById('statPipeline').textContent=money(pipeline);document.getElementById('statPipelineHint').textContent=`${planned.length} ${plural(planned.length,'автомобиль','автомобиля','автомобилей')}`;
  document.getElementById('monthCalcLabel').textContent=monthTitle(key);document.getElementById('monthBreakdown').innerHTML=`<div class="breakdown-row"><span>Мой заработок с автомобилей</span><strong>${money(m.dealPay)}</strong></div><div class="breakdown-row"><span>Оклад</span><strong>${m.cfg.enabled?money(m.salary):'Выключен'}</strong></div>${m.cfg.enabled&&m.cfg.absorbed?`<div class="breakdown-row"><span>Поглощено заработком</span><strong>− ${money(m.absorbedPart)}</strong></div>`:''}<div class="breakdown-row total"><span>Итого к выплате</span><strong>${money(m.total)}</strong></div><div class="formula-hint">${m.cfg.enabled?(m.cfg.absorbed?'Оклад страхует минимальную выплату, но не складывается с заработком.':'Оклад прибавляется к заработку со сделок.'):'Оклад в этом месяце не учитывается.'}</div>`;
  renderChart();renderRecent();renderTeamEarnings(key);
}
function renderChart(){const now=new Date(),keys=[];for(let i=5;i>=0;i--){const d=new Date(now.getFullYear(),now.getMonth()-i,1);keys.push(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`)}const vals=keys.map(k=>calcMonth(k).total),max=Math.max(...vals,1);document.getElementById('earningsChart').innerHTML=keys.map((k,i)=>`<div class="bar-wrap"><span class="bar-value">${vals[i]?Math.round(vals[i]/1000)+'к':''}</span><div class="bar" style="height:${Math.max(2,vals[i]/max*145)}px"></div><span class="bar-label">${MONTHS_SHORT[Number(k.slice(5))-1]}</span></div>`).join('')}
function distributionHtml(calc){if(calc.legacy)return `<span class="legacy-note">Старая схема · ${escapeHtml(ownName())}: ${money(calc.ownTotal)}</span>`;if(!calc.distributions.length)return '<span class="muted-cell">Участники не указаны</span>';return `<div class="distribution-list">${calc.distributions.filter(row=>row.total||row.delta).map(row=>`<span><b>${escapeHtml(row.name)}</b> ${money(row.total)}${Math.abs(row.delta)>.01?` <i class="delta ${row.delta>0?'positive':'negative'}" title="Разница с распределением по этапам">${signedMoney(row.delta)}</i>`:''}</span>`).join('')}</div>`}
function saleMessage(d){const responsible=d.responsible||d.acceptedBy||'—',seller=d.soldBy||'—',days=Number(d.avitoDays)||0;return `Продажа: ${d.car||'—'}\nГод выпуска: ${d.year||'—'}\nЦена продажи: ${plainNumber(d.salePrice)}\nЦена машины: ${plainNumber(d.avitoPrice)}\nНа руки собственнику: ${plainNumber(d.ownerAmount)}\nОтветственный: ${responsible}\nПродал: ${seller}\nНа Авито: ${days} ${plural(days,'день','дня','дней')}\nКомментарии: ${d.note||'—'}`}
async function copyDealMessage(d){const text=saleMessage(d);try{await navigator.clipboard.writeText(text)}catch{const area=document.createElement('textarea');area.value=text;area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.select();document.execCommand('copy');area.remove()}toast('Сообщение о продаже скопировано')}
function dealRow(d,actions=true){const c=calcDeal(d),director=calcDirector(d,c),settlement=calcSettlement(d,c,director),mine=settlement.rows.find(row=>row.mine),mode=d.allocationVersion?(d.allocationMode==='equal'?'поровну вручную':'по этапам'):(d.participation==='full'?'полный цикл':'один этап');const settlementLabel=d.settlementVersion?(mine&&Math.abs(mine.balance)>.01?(mine.balance>0?`Мне должны: ${money(mine.balance)}`:`Мне вернуть: ${money(Math.abs(mine.balance))}`):(settlement.closed?'Расчёты закрыты':`Не закрыто: ${money(settlement.owed)}`)):'';return `<tr><td><div class="car-cell"><strong>${escapeHtml(d.car)}</strong><span>${d.type==='buyout'?'Выкуп':'Комиссия'} · ${mode}</span>${director.enabled?`<small>Директору чистыми: ${money(director.selectedNet)}</small>`:''}${settlementLabel?`<small class="settlement-table-status">${settlementLabel}</small>`:''}</div></td><td><span class="badge ${d.status}">${d.status==='sold'?'Реализовано':'В работе'}</span></td><td>${d.date?new Date(d.date+'T00:00:00').toLocaleDateString('ru-RU'):'—'}</td><td>${distributionHtml(c)}</td><td class="amount">${money(c.ownTotal)}</td>${actions?`<td><div class="table-actions"><button class="icon-mini" data-copy="${d.id}" title="Копировать сообщение">▣</button><button class="icon-mini" data-edit="${d.id}" title="Изменить">✎</button><button class="icon-mini" data-delete="${d.id}" title="Удалить">×</button></div></td>`:''}</tr>`}
function tableHtml(items,actions=true){if(!items.length)return '<div class="empty-state"><strong>Пока здесь пусто</strong>Добавьте первую сделку — расчёт появится автоматически.</div>';return `<div style="overflow:auto"><table class="data-table"><thead><tr><th>Автомобиль</th><th>Статус</th><th>Дата</th><th>Распределение</th><th>Мой заработок</th>${actions?'<th></th>':''}</tr></thead><tbody>${items.map(d=>dealRow(d,actions)).join('')}</tbody></table></div>`}
function renderRecent(){const sorted=[...state.deals].sort((a,b)=>(b.updatedAt||b.date||'').localeCompare(a.updatedAt||a.date||'')).slice(0,5);document.getElementById('recentDeals').innerHTML=tableHtml(sorted,false)}
function renderDeals(){const q=document.getElementById('dealSearch').value.trim().toLowerCase(),status=document.getElementById('statusFilter').value,month=document.getElementById('dealMonthFilter').value;const filtered=[...state.deals].filter(d=>(status==='all'||d.status===status)&&(month==='all'||dateToMonth(d.date)===month)&&`${d.car} ${d.year||''} ${d.soldBy} ${d.acceptedBy} ${d.responsible||''} ${d.equalParticipants||''} ${d.note}`.toLowerCase().includes(q)).sort((a,b)=>(b.date||'').localeCompare(a.date||''));document.getElementById('dealsTable').innerHTML=tableHtml(filtered,true)}
function renderTeamEarnings(key){
  const deals=state.deals.filter(d=>d.status==='sold'&&dateToMonth(d.date)===key),map=new Map(),summary={deals:0,margin:0,managerPay:0,capital:0,capitalDays:0,beforeTax:0,tax:0,net:0,bank:0,inflation:0,real:0,advantage:0};
  const ensure=row=>{const id=row.name.toLocaleLowerCase('ru-RU');if(!map.has(id))map.set(id,{name:row.name,total:0,directorValue:0,directorBeforeTax:0,taxValue:0,grossValue:0,bankValue:0,delta:0,buyDeals:0,saleDeals:0,dealIds:new Set()});return map.get(id)};
  deals.forEach(deal=>{
    const calc=calcDeal(deal),director=calcDirector(deal,calc);
    calc.distributions.forEach(row=>{const item=ensure(row);item.total+=row.total;item.delta+=row.delta||0;if(row.buy)item.buyDeals++;if(row.sale)item.saleDeals++;if(row.total)item.dealIds.add(deal.id)});
    if(!director.enabled)return;
    summary.deals++;summary.margin+=director.margin;summary.managerPay+=director.managerPay;summary.capital+=director.capital;summary.capitalDays+=director.capital*director.days;summary.beforeTax+=director.beforeTax;summary.tax+=deal.directorTaxEnabled===false?0:director.tax;summary.net+=director.selectedNet;summary.bank+=director.bankNet;summary.inflation+=director.inflationLoss;summary.real+=director.realProfit;summary.advantage+=director.advantage;
    director.contributions.forEach(row=>{const item=ensure(row);item.directorValue+=row.value;item.directorBeforeTax+=row.beforeTaxValue;item.taxValue+=row.taxValue;item.grossValue+=row.grossValue;item.bankValue+=row.bankValue;item.dealIds.add(deal.id)});
  });
  const rows=[...map.values()].sort((a,b)=>(b.total+b.directorValue)-(a.total+a.directorValue)),avgDays=summary.capital?summary.capitalDays/summary.capital:0,roi=summary.capital?summary.net/summary.capital:0,annual=summary.capitalDays?summary.net/(summary.capitalDays/365):0;
  if(!rows.length){document.getElementById('teamEarnings').innerHTML='<div class="empty-state"><strong>Нет распределений за этот месяц</strong>Они появятся после реализации сделок.</div>';return}
  const directorSummary=summary.deals?`<div class="team-summary"><div class="team-summary-head"><strong>Итог директора за ${monthTitle(key)}</strong><span>${summary.deals} ${plural(summary.deals,'сделка','сделки','сделок')} с аналитикой</span></div><div class="team-summary-grid"><div><span>Маржа сделок</span><b>${money(summary.margin)}</b></div><div><span>Выплаты команде</span><b>− ${money(summary.managerPay)}</b></div><div><span>До налога</span><b>${money(summary.beforeTax)}</b></div><div class="accent"><span>Чистыми директору</span><b>${money(summary.net)}</b></div><div><span>УСН</span><b>− ${money(summary.tax)}</b></div><div><span>Оборот капитала</span><b>${money(summary.capital)}</b></div><div><span>Средний срок</span><b>${new Intl.NumberFormat('ru-RU',{maximumFractionDigits:1}).format(avgDays)} дн.</b></div><div><span>Доходность оборота</span><b>${percent(roi*100,2)}</b></div><div><span>Простая годовая</span><b>${percent(annual*100)}</b></div><div><span>Вклад чистыми</span><b>${money(summary.bank)}</b></div><div><span>Лучше вклада</span><b class="positive">${money(summary.advantage)}</b></div><div><span>Реальная прибыль</span><b>${money(summary.real)}</b></div></div></div>`:'';
  const cards=rows.map((row,index)=>{const count=row.dealIds.size,combined=row.total+row.directorValue,ratio=row.total?row.directorValue/row.total:0,avg=count?row.directorValue/count:0,share=summary.net?row.directorValue/summary.net:0;return `<article class="manager-benefit-card"><div class="manager-benefit-head"><span class="team-rank">${index+1}</span><div><strong>${escapeHtml(row.name)}${sameManager(row.name,ownName())?' <em>это я</em>':''}</strong><small>${count} ${plural(count,'сделка','сделки','сделок')} · выкуп ${row.buyDeals} · продажа ${row.saleDeals}</small></div><span class="support ${row.delta>0?'positive':row.delta<0?'negative':''}">${Math.abs(row.delta)>.01?(row.delta>0?'Поддержали ':'Поделился ')+money(Math.abs(row.delta)):'По этапам'}</span></div><div class="manager-main-values"><div><span>Заработал себе</span><b>${money(row.total)}</b></div><div class="director-benefit"><span>Принёс директору</span><b>${money(row.directorValue)}</b></div><div><span>Создано вместе</span><b>${money(combined)}</b></div></div><div class="manager-extra-values"><div><span>Маржа в его этапах</span><b>${money(row.grossValue)}</b></div><div><span>Директору до налога</span><b>${money(row.directorBeforeTax)}</b></div><div><span>Его доля УСН</span><b>${money(row.taxValue)}</b></div><div><span>Среднее директору</span><b>${money(avg)}</b></div><div><span>Польза / выплата</span><b>${percent(ratio*100)}</b></div><div><span>Доля чистой прибыли</span><b>${percent(share*100)}</b></div></div></article>`}).join('');
  document.getElementById('teamEarnings').innerHTML=`${directorSummary}<div class="team-section-title"><strong>Результат каждого менеджера</strong><span>Личные выплаты и вклад в прибыль бизнеса</span></div><div class="manager-benefit-grid">${cards}</div><p class="team-hint">Прибыль директору распределяется аналитически по участию: 50% относится к выкупу и 50% к продаже. Оборот капитала — сумма вложений по сделкам, а не одновременный остаток денег.</p>`;
}
function renderMonths(){const keys=allMonthKeys();document.getElementById('monthsGrid').innerHTML=keys.map(k=>{const m=calcMonth(k);return `<article class="month-card ${k===currentMonth()?'current':''}"><div class="month-card-head"><div><h3>${monthTitle(k)}</h3><span class="mini-status">${m.deals.length} ${plural(m.deals.length,'сделка','сделки','сделок')}</span></div><span class="badge ${k===currentMonth()?'planned':'sold'}">${k===currentMonth()?'Текущий':'Закрытый'}</span></div><div class="month-total">${money(m.total)}</div><div class="month-meta"><div><span>Мои со сделок</span><strong>${money(m.dealPay)}</strong></div><div><span>Оклад</span><strong>${m.cfg.enabled?money(m.salary):'Выкл.'}</strong></div><div><span>Режим</span><strong>${m.cfg.enabled?(m.cfg.absorbed?'Поглощается':'+ сверху'):'Без оклада'}</strong></div></div><button class="month-edit" data-month="${k}">Настроить месяц</button></article>`}).join('')}
function renderSettings(){const s=state.settings;document.getElementById('rateCommissionFull').value=s.commissionFull;document.getElementById('rateCommissionPart').value=s.commissionPart;document.getElementById('rateBuyoutFull').value=s.buyoutFull;document.getElementById('rateBuyoutPart').value=s.buyoutPart;document.getElementById('rateCredit').value=s.credit;document.getElementById('defaultSalary').value=s.defaultSalary;document.getElementById('ownManagerName').value=s.ownManagerName||'Я'}
function renderAll(){fillMonthSelects();renderDashboard();renderDeals();renderMonths();renderSettings()}

const dealDialog=document.getElementById('dealDialog');
let directorCapitalTouched=false,directorDaysTouched=false;
let managerPaymentsDraft={};
let fixedPaymentsDraft={owner:0,director:0,tax:0,expenses:0};
const participantGroupIds=['acceptedByOptions','soldByOptions','equalParticipantsOptions'];
function selectedParticipants(groupId){return [...document.querySelectorAll(`#${groupId} input[type="checkbox"]:checked`)].map(input=>input.value)}
function currentParticipantSelections(){return Object.fromEntries(participantGroupIds.map(id=>[id,selectedParticipants(id)]))}
function participantOptionHtml(name,selected){return `<label class="participant-chip"><input type="checkbox" value="${escapeHtml(name)}" ${selected.some(item=>sameManager(item,name))?'checked':''}><span>${escapeHtml(name)}${sameManager(name,ownName())?' <em>я</em>':''}</span></label>`}
function renderParticipantSelectors(selections={}){const names=managerCatalog();participantGroupIds.forEach(id=>{const selected=selections[id]||[];document.getElementById(id).innerHTML=names.map(name=>participantOptionHtml(name,selected)).join('')})}
function openDeal(id){
  const d=id?state.deals.find(x=>x.id===id):{id:'',car:'',year:'',status:'planned',date:new Date().toISOString().slice(0,10),type:'buyout',allocationVersion:2,allocationMode:'stages',acceptedBy:'Я',soldBy:'Я',equalParticipants:'Я',avitoPrice:0,salePrice:0,ownerAmount:0,avitoDays:0,responsible:'',margin:0,creditCommission:0,note:'',directorEnabled:true,directorCapital:0,directorDays:0,directorExpenses:0,directorTaxRate:15,directorSubtractManagers:true,directorTaxEnabled:true,bankRate:17,inflationRate:5.2,settlementVersion:1,buyerReceivedActual:0,ownerPaidActual:0,directorPaidActual:0,taxPaidActual:0,expensesPaidActual:0,managerActualPayments:{}};
  document.getElementById('dealModalTitle').textContent=id?'Изменить сделку':'Новая сделка';document.getElementById('dealId').value=d.id;document.getElementById('carName').value=d.car;document.getElementById('carYear').value=d.year||'';document.getElementById('dealStatus').value=d.status;document.getElementById('dealDate').value=d.date||'';document.getElementById('dealType').value=d.type;
  document.getElementById('allocationMode').value=d.allocationMode||'stages';
  const accepted=parseParticipants(d.acceptedBy),sold=parseParticipants(d.soldBy),equal=parseParticipants(d.equalParticipants);renderParticipantSelectors({acceptedByOptions:accepted,soldByOptions:sold,equalParticipantsOptions:equal.length?equal:[...new Set([...accepted,...sold])]});
  document.getElementById('newManagerRow').classList.remove('visible');document.getElementById('newManagerName').value='';
  document.getElementById('avitoPrice').value=d.avitoPrice||0;document.getElementById('salePrice').value=d.salePrice||0;document.getElementById('ownerAmount').value=d.ownerAmount||0;document.getElementById('avitoDays').value=d.avitoDays||0;document.getElementById('dealResponsible').value=d.responsible||'';document.getElementById('carMargin').value=d.margin||0;document.getElementById('creditCommission').value=d.creditCommission||0;document.getElementById('dealNote').value=d.note||'';
  document.getElementById('directorEnabled').checked=Boolean(d.directorEnabled);document.getElementById('directorCapital').value=d.directorCapital||d.ownerAmount||0;document.getElementById('directorDays').value=d.directorDays||d.avitoDays||1;document.getElementById('directorExpenses').value=d.directorExpenses||0;document.getElementById('directorTaxRate').value=d.directorTaxRate??15;document.getElementById('directorSubtractManagers').checked=d.directorSubtractManagers!==false;document.getElementById('directorTaxEnabled').checked=d.directorTaxEnabled!==false;document.getElementById('bankRate').value=d.bankRate??17;document.getElementById('inflationRate').value=d.inflationRate??5.2;
  document.getElementById('settlementBuyerReceived').value=d.buyerReceivedActual||0;managerPaymentsDraft={...(d.managerActualPayments||{})};fixedPaymentsDraft={owner:Number(d.ownerPaidActual)||0,director:Number(d.directorPaidActual)||0,tax:Number(d.taxPaidActual)||0,expenses:Number(d.expensesPaidActual)||0};directorCapitalTouched=Boolean(d.directorCapital);directorDaysTouched=Boolean(d.directorDays);updateAllocationMode();updateDirectorControls();updateLiveCalc();dealDialog.showModal();
}
function formDeal(){return{id:document.getElementById('dealId').value||crypto.randomUUID(),car:document.getElementById('carName').value.trim(),year:num('carYear')||'',status:document.getElementById('dealStatus').value,date:document.getElementById('dealDate').value,type:document.getElementById('dealType').value,allocationVersion:2,allocationMode:document.getElementById('allocationMode').value,acceptedBy:selectedParticipants('acceptedByOptions').join(', '),soldBy:selectedParticipants('soldByOptions').join(', '),equalParticipants:selectedParticipants('equalParticipantsOptions').join(', '),avitoPrice:num('avitoPrice'),salePrice:num('salePrice'),ownerAmount:num('ownerAmount'),avitoDays:num('avitoDays'),responsible:document.getElementById('dealResponsible').value.trim(),margin:num('carMargin'),creditCommission:num('creditCommission'),note:document.getElementById('dealNote').value.trim(),directorEnabled:document.getElementById('directorEnabled').checked,directorCapital:num('directorCapital'),directorDays:num('directorDays'),directorExpenses:num('directorExpenses'),directorTaxRate:num('directorTaxRate'),directorSubtractManagers:document.getElementById('directorSubtractManagers').checked,directorTaxEnabled:document.getElementById('directorTaxEnabled').checked,bankRate:num('bankRate'),inflationRate:num('inflationRate'),settlementVersion:1,buyerReceivedActual:num('settlementBuyerReceived'),ownerPaidActual:fixedPaymentsDraft.owner||0,directorPaidActual:fixedPaymentsDraft.director||0,taxPaidActual:fixedPaymentsDraft.tax||0,expensesPaidActual:fixedPaymentsDraft.expenses||0,managerActualPayments:{...managerPaymentsDraft},updatedAt:new Date().toISOString()}}
function autoMarginFromPricing(){const sale=document.getElementById('salePrice'),owner=document.getElementById('ownerAmount');if(sale.value!==''&&owner.value!==''){document.getElementById('carMargin').value=Math.max(0,(Number(sale.value)||0)-(Number(owner.value)||0));document.getElementById('marginAutoHint').classList.add('active')}if(!directorCapitalTouched)document.getElementById('directorCapital').value=Number(owner.value)||0;updateLiveCalc()}
function syncDirectorDays(){if(!directorDaysTouched)document.getElementById('directorDays').value=Math.max(1,num('avitoDays'));updateLiveCalc()}
function updateAllocationMode(){document.getElementById('equalParticipantsWrap').classList.toggle('visible',document.getElementById('allocationMode').value==='equal')}
function updateDirectorControls(){document.getElementById('directorControls').classList.toggle('disabled',!document.getElementById('directorEnabled').checked)}
function updateLiveCalc(){
  const d=formDeal(),c=calcDeal(d);document.getElementById('liveRate').textContent=`${c.rate}%`;document.getElementById('liveCarPay').textContent=money(c.carPool);document.getElementById('liveCreditPay').textContent=money(c.creditPool);document.getElementById('liveTotal').textContent=money(c.ownTotal);
  const detail=c.distributions.length?c.distributions.map(row=>`<div><span><strong>${escapeHtml(row.name)}</strong>${row.buy?` · выкуп ${money(row.buy)}`:''}${row.sale?` · продажа ${money(row.sale)}`:''}${row.equal?` · поровну ${money(row.equal)}`:''}${row.credit?` · кредит ${money(row.credit)}`:''}</span><b>${money(row.total)}</b>${Math.abs(row.delta)>.01?`<small class="${row.delta>0?'positive':'negative'}">${row.delta>0?'поддержали':'поделился'} на ${money(Math.abs(row.delta))}</small>`:''}</div>`).join(''):'<p>Укажите участников — здесь появится распределение.</p>';
  document.getElementById('allocationPreview').innerHTML=`<div class="allocation-title"><strong>Распределение сделки</strong><span>${d.allocationMode==='equal'?'Ручное деление':'По этапам'}</span></div>${detail}${c.unallocated?`<div class="unallocated"><span>Не распределено</span><b>${money(c.unallocated)}</b></div>`:''}`;updateDirectorPreview(d,c);updateSettlementPreview(d,c);
}
function updateDirectorPreview(d,c){
  const x=calcDirector(d,c),el=document.getElementById('directorPreview');if(!x.enabled){el.innerHTML='<p>Расчёт директора выключен для этой сделки.</p>';return}
  const people=x.contributions.length?x.contributions.map(row=>`<span><b>${escapeHtml(row.name)}</b><em>${money(row.value)} директору</em></span>`).join(''):'<p>Отметьте участников выкупа и продажи, чтобы распределить вклад.</p>';
  el.innerHTML=`<div class="director-kpis"><div><span>Маржа сделки</span><b>${money(x.margin)}</b></div><div><span>Менеджерам</span><b>− ${money(x.managerPay)}</b></div><div><span>До налога</span><b>${money(x.beforeTax)}</b></div><div class="director-net"><span>Чистыми директору</span><b>${money(x.selectedNet)}</b></div></div><div class="director-detail"><div><span>УСН ${percent(x.taxRate)}</span><b>− ${money(x.tax)}</b></div><div><span>Доходность за ${x.days} ${plural(x.days,'день','дня','дней')}</span><b>${percent(x.periodReturn*100,2)}</b></div><div><span>Простая годовая</span><b>${percent(x.annualSimple*100)}</b></div><div><span>С капитализацией</span><b>${percent(x.annualCompound*100)}</b></div><div><span>Вклад чистыми</span><b>${money(x.bankNet)}</b></div><div><span>Лучше вклада на</span><b class="positive">${money(x.advantage)}</b></div><div><span>Потеря от инфляции</span><b>− ${money(x.inflationLoss)}</b></div><div><span>Реальная прибыль</span><b>${money(x.realProfit)}</b></div></div><div class="director-contributions"><strong>Кто сколько принёс директору</strong><div>${people}</div>${Math.abs(x.unassigned)>.01?`<small>Не распределено по участникам: ${money(x.unassigned)}</small>`:''}</div>`;
}
function settlementStatus(row){if(Math.abs(row.balance)<.01)return '<span class="settlement-status closed">Расчёт закрыт</span>';return row.balance>0?`<span class="settlement-status owed">Ещё выдать ${money(row.balance)}</span>`:`<span class="settlement-status return">Вернуть ${money(Math.abs(row.balance))}</span>`}
function renderSettlementSummary(s){
  const buyerText=Math.abs(s.buyerBalance)<.01?'<span class="settlement-status closed">Получено полностью</span>':s.buyerBalance>0?`<span class="settlement-status owed">Покупатель должен ${money(s.buyerBalance)}</span>`:`<span class="settlement-status return">Вернуть покупателю ${money(Math.abs(s.buyerBalance))}</span>`;
  document.getElementById('settlementBuyerDue').textContent=money(s.buyerDue);document.getElementById('settlementSummary').innerHTML=`<div class="settlement-buyer-status">${buyerText}</div><div class="settlement-kpis"><div><span>К выдаче всего</span><b>${money(s.totalDue)}</b></div><div><span>Фактически выдано</span><b>${money(s.totalActual)}</b></div><div><span>Ещё должны людям</span><b>${money(s.owed)}</b></div><div><span>Нужно вернуть</span><b>${money(s.toReturn)}</b></div><div class="${s.cashBalance>=0?'cash-positive':'cash-negative'}"><span>Денег осталось по факту</span><b>${money(s.cashBalance)}</b></div><div class="${s.closed?'settlement-closed':'settlement-open'}"><span>Статус сделки</span><b>${s.closed?'Все расчёты закрыты':'Есть незакрытые расчёты'}</b></div></div>`;
}
function updateSettlementPreview(d,c){
  const s=calcSettlement(d,c);
  document.getElementById('settlementRows').innerHTML=s.rows.map(row=>`<div class="settlement-row ${row.mine?'mine':''}"><div><strong>${escapeHtml(row.name)}${row.mine?' <em>это я</em>':''}</strong><small>${row.type==='manager'?'Вознаграждение менеджера':row.type==='owner'?'Деньги за автомобиль':row.type==='director'?'Чистая прибыль':'Обязательный платёж'}</small></div><b>${money(row.due)}</b><div class="suffix-input money"><input type="number" min="0" step="1" value="${row.actual}" aria-label="Фактически выдано ${escapeHtml(row.name)}" ${row.type==='manager'?`data-manager-payment="${escapeHtml(row.key)}"`:`data-fixed-payment="${row.type}"`}><span>₽</span></div><div>${settlementStatus(row)}</div></div>`).join('');
  renderSettlementSummary(s);
}
function refreshSettlementActuals(e){if(e?.target?.dataset.managerPayment!==undefined)managerPaymentsDraft[e.target.dataset.managerPayment]=Number(e.target.value)||0;if(e?.target?.dataset.fixedPayment!==undefined)fixedPaymentsDraft[e.target.dataset.fixedPayment]=Number(e.target.value)||0;const d=formDeal(),s=calcSettlement(d);[...document.querySelectorAll('.settlement-row')].forEach((element,index)=>{if(s.rows[index])element.lastElementChild.innerHTML=settlementStatus(s.rows[index])});renderSettlementSummary(s)}
document.getElementById('newDealBtn').onclick=()=>openDeal();
['dealType','allocationMode','carMargin','creditCommission'].forEach(id=>document.getElementById(id).addEventListener('input',()=>{if(id==='allocationMode')updateAllocationMode();updateLiveCalc()}));
['salePrice','ownerAmount'].forEach(id=>document.getElementById(id).addEventListener('input',autoMarginFromPricing));
document.getElementById('avitoDays').addEventListener('input',syncDirectorDays);
['directorExpenses','directorTaxRate','bankRate','inflationRate'].forEach(id=>document.getElementById(id).addEventListener('input',updateLiveCalc));
document.getElementById('directorCapital').addEventListener('input',()=>{directorCapitalTouched=true;updateLiveCalc()});
document.getElementById('directorDays').addEventListener('input',()=>{directorDaysTouched=true;updateLiveCalc()});
['directorSubtractManagers','directorTaxEnabled'].forEach(id=>document.getElementById(id).addEventListener('change',updateLiveCalc));
document.getElementById('directorEnabled').addEventListener('change',()=>{updateDirectorControls();updateLiveCalc()});
document.getElementById('settlementBuyerReceived').addEventListener('input',refreshSettlementActuals);
document.getElementById('settlementRows').addEventListener('input',refreshSettlementActuals);
document.getElementById('settlementFillCalculatedBtn').onclick=()=>{const d=formDeal(),c=calcDeal(d),s=calcSettlement(d,c);document.getElementById('settlementBuyerReceived').value=s.buyerDue;s.rows.forEach(row=>{if(row.type==='manager')managerPaymentsDraft[row.key]=row.due;else fixedPaymentsDraft[row.type]=row.due});updateLiveCalc();toast('Фактические суммы заполнены по расчёту')};
participantGroupIds.forEach(id=>document.getElementById(id).addEventListener('change',updateLiveCalc));
document.getElementById('showAddManagerBtn').onclick=()=>{document.getElementById('newManagerRow').classList.add('visible');document.getElementById('newManagerName').focus()};
document.getElementById('cancelAddManagerBtn').onclick=()=>{document.getElementById('newManagerRow').classList.remove('visible');document.getElementById('newManagerName').value=''};
function addManager(){const name=cleanManagerName(document.getElementById('newManagerName').value);if(!name)return;const selections=currentParticipantSelections(),names=managerCatalog();if(!names.some(item=>sameManager(item,name))){state.settings.managerNames=[...(Array.isArray(state.settings.managerNames)?state.settings.managerNames:DEFAULT_MANAGERS),name];saveState()}renderParticipantSelectors(selections);document.getElementById('newManagerRow').classList.remove('visible');document.getElementById('newManagerName').value='';toast(names.some(item=>sameManager(item,name))?'Такой участник уже есть':'Участник добавлен')}
document.getElementById('addManagerBtn').onclick=addManager;
document.getElementById('newManagerName').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();addManager()}});
document.getElementById('copyCurrentDealBtn').onclick=()=>copyDealMessage(formDeal());
document.getElementById('dealForm').addEventListener('submit',e=>{e.preventDefault();const d=formDeal();if(!d.car)return;const idx=state.deals.findIndex(x=>x.id===d.id);if(idx>=0)state.deals[idx]=d;else state.deals.push(d);if(d.status==='sold')ensureMonth(dateToMonth(d.date));saveState();dealDialog.close();renderAll();if(String(d.id).startsWith('SALE-')&&window.parent!==window){window.parent.postMessage({type:'TITAN_PAYMENT_SAVE',requestId:crypto.randomUUID(),saleId:d.id,deal:d},location.origin);toast('Сохраняем расчёт в общей базе…')}else toast(idx>=0?'Сделка обновлена':'Сделка добавлена')});
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
document.getElementById('dealsTable').addEventListener('click',e=>{const edit=e.target.dataset.edit,del=e.target.dataset.delete,copy=e.target.dataset.copy;if(edit)openDeal(edit);if(copy){const d=state.deals.find(item=>item.id===copy);if(d)copyDealMessage(d)}if(del&&String(del).startsWith('SALE-'))toast('Продажу из общей базы нельзя удалить в калькуляторе');else if(del&&confirm('Удалить эту сделку?')){state.deals=state.deals.filter(d=>d.id!==del);saveState();renderAll();toast('Сделка удалена')}});

const monthDialog=document.getElementById('monthDialog');
document.getElementById('monthsGrid').addEventListener('click',e=>{const key=e.target.dataset.month;if(!key)return;const cfg=ensureMonth(key);document.getElementById('monthKey').value=key;document.getElementById('monthModalTitle').textContent=monthTitle(key);document.getElementById('monthSalary').value=cfg.salary;document.getElementById('salaryEnabled').checked=cfg.enabled;document.getElementById('salaryAbsorbed').checked=cfg.absorbed;monthDialog.showModal()});
document.getElementById('monthForm').addEventListener('submit',e=>{e.preventDefault();const key=document.getElementById('monthKey').value;state.months[key]={salary:num('monthSalary'),enabled:document.getElementById('salaryEnabled').checked,absorbed:document.getElementById('salaryAbsorbed').checked};saveState();monthDialog.close();renderAll();toast('Настройки месяца сохранены')});
document.getElementById('saveRatesBtn').onclick=()=>{state.settings={...state.settings,commissionFull:num('rateCommissionFull'),commissionPart:num('rateCommissionPart'),buyoutFull:num('rateBuyoutFull'),buyoutPart:num('rateBuyoutPart'),credit:num('rateCredit')};saveState();renderAll();toast('Ставки сохранены')};
document.getElementById('saveSalaryBtn').onclick=()=>{state.settings.defaultSalary=num('defaultSalary');state.settings.ownManagerName=document.getElementById('ownManagerName').value.trim()||'Я';saveState();renderAll();toast('Оклад и имя сохранены')};
document.getElementById('exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`titan-auto-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};
document.getElementById('importInput').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(!data.settings||!Array.isArray(data.deals))throw new Error();state={settings:{...defaults.settings,...data.settings},deals:data.deals,months:data.months||{}};saveState();renderAll();toast('Данные импортированы')}catch{alert('Не удалось прочитать файл резервной копии.')}e.target.value=''};
document.getElementById('clearDataBtn').onclick=()=>{if(confirm('Удалить все сделки и настройки? Это действие нельзя отменить.')){state=structuredClone(defaults);saveState();renderAll();toast('Все данные удалены')}};
document.getElementById('dashboardPeriod').onchange=renderDashboard;
['dealSearch','statusFilter','dealMonthFilter'].forEach(id=>document.getElementById(id).addEventListener('input',renderDeals));
function saleDeal(sale,vehicle={}){
  let stored={};try{const payload=typeof sale.payload_json==='string'?JSON.parse(sale.payload_json||'{}'):(sale.payload_json||{});stored=payload.calculator_state||{}}catch{}
  const accepted=cleanManagerName(sale.accepted_by||sale.responsible_manager||sale.manager||''),sold=cleanManagerName(sale.sold_by||sale.manager||''),managerActual={};
  if(sold&&Number(sale.actual_manager_payment))managerActual[sold.toLocaleLowerCase('ru-RU')]=Number(sale.actual_manager_payment);
  if(accepted&&Number(sale.actual_director_payment))managerActual[accepted.toLocaleLowerCase('ru-RU')]=(managerActual[accepted.toLocaleLowerCase('ru-RU')]||0)+Number(sale.actual_director_payment);
  const commission=sale.deal_type==='commission',margin=commission?Number(sale.commission)||Number(sale.margin)||0:Number(sale.margin)||Math.max(0,(Number(sale.sale_price)||0)-(Number(sale.purchase_price)||0));
  return{...stored,id:sale.sale_id,vehicleId:sale.vehicle_id,car:stored.car||[vehicle.brand,vehicle.model].filter(Boolean).join(' ')||sale.vehicle_id,year:stored.year||vehicle.year||'',status:'sold',date:String(sale.sale_date||stored.date||sale.created_at||'').slice(0,10),type:commission?'commission':'buyout',allocationVersion:2,allocationMode:stored.allocationMode||'stages',acceptedBy:sale.accepted_by||stored.acceptedBy||accepted,soldBy:sale.sold_by||stored.soldBy||sold,avitoPrice:Number(stored.avitoPrice)||Number(vehicle.sale_price)||Number(sale.sale_price)||0,salePrice:Number(sale.sale_price)||Number(stored.salePrice)||0,ownerAmount:Number(sale.owner_amount)||Number(stored.ownerAmount)||0,avitoDays:Number(sale.avito_days)||Number(stored.avitoDays)||0,responsible:sale.responsible_manager||stored.responsible||accepted,margin,creditCommission:Number(sale.credit_commission)||Number(stored.creditCommission)||0,note:sale.comment||stored.note||'',directorExpenses:Number(sale.expenses)||Number(stored.directorExpenses)||0,buyerReceivedActual:Number(sale.actual_buyer_payment)||Number(stored.buyerReceivedActual)||0,ownerPaidActual:Number(sale.actual_owner_payment)||Number(stored.ownerPaidActual)||0,taxPaidActual:Number(sale.tax)||Number(stored.taxPaidActual)||0,expensesPaidActual:Number(stored.expensesPaidActual)||Number(sale.expenses)||0,managerActualPayments:Object.keys(managerActual).length?managerActual:(stored.managerActualPayments||{}),updatedAt:stored.updatedAt||sale.created_at||new Date().toISOString()};
}
addEventListener('message',event=>{if(event.origin!==location.origin||event.data?.type!=='TITAN_PAYMENTS_LOAD')return;const message=event.data,vehicles=Object.fromEntries((message.vehicles||[]).map(vehicle=>[vehicle.vehicle_id,vehicle])),canonical=(message.sales||[]).map(sale=>saleDeal(sale,vehicles[sale.vehicle_id]||{})),local=state.deals.filter(deal=>!String(deal.id||'').startsWith('SALE-'));state.deals=[...canonical,...local];const managers=(message.company?.managers||[]).map(item=>item.name).filter(Boolean);if(managers.length)state.settings.managerNames=[...new Set([...state.settings.managerNames,...managers])];saveState();renderAll();const footer=document.querySelector('.sidebar-footer');if(footer)footer.innerHTML=`<span class="status-dot"></span>Синхронизировано с TITAN AUTO · ${canonical.length} сделок`;toast(`Загружено из общей базы: ${canonical.length} сделок`)});
addEventListener('message',event=>{if(event.origin!==location.origin||event.data?.type!=='TITAN_PAYMENT_SAVE_RESULT')return;toast(event.data.ok?'Расчёт сохранён в общей базе':`Не удалось сохранить: ${event.data.error||'ошибка'}`)});
renderAll();
