(() => {
  const defaults = {
    fields: {brand:'BMW',model:'X3',trim:'xDrive20i',year:'2014',mileage:'210000',transmission:'AT',fuel:'БЕНЗИН',engine:'2.0',power:'184',drive:'ПОЛНЫЙ ПРИВОД',price:'1830000',salePrice:'1750000',saleType:'НА КОМИССИИ',status:'ЗАБРОНИРОВАН',benefits:'1 владелец, Честный пробег, Обслужен',arrivalDate:'2026-08-29',qrUrl:'https://www.avito.ru/'},
    toggles:{labels:true,discount:false,saleType:true,status:false,benefits:true,payment:true,stock:true,qr:true,mono:false},
    payments:['Наличные','Кредит','Трейд-ин','Обмен'],paymentCustom:'',qrImage:'',managerIndex:0,
    managers:[{name:'Менеджер',phone:''}]
  };
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const copy=o=>JSON.parse(JSON.stringify(o));
  const RECORDS_KEY='titan-price-tags-v1';
  let state=load(),qrKey='',records=loadRecords(),currentRecordId=null;
  function normalizeState(source){const s=source&&typeof source==='object'?source:{};const savedFields={...(s.fields||{})};if(!Object.prototype.hasOwnProperty.call(savedFields,'brand')){const legacy=String(savedFields.model||'').trim().split(/\s+/);savedFields.brand=legacy.shift()||defaults.fields.brand;savedFields.model=legacy.join(' ')||defaults.fields.model}return {...copy(defaults),...s,fields:{...defaults.fields,...savedFields},toggles:{...defaults.toggles,...(s.toggles||{})},payments:Array.isArray(s.payments)?s.payments:copy(defaults.payments),managers:Array.isArray(s.managers)&&s.managers.length?s.managers:copy(defaults.managers)}}
  function load(){try{return normalizeState(JSON.parse(localStorage.getItem('titan-price-tag-v3')))}catch{return copy(defaults)}}
  function save(){localStorage.setItem('titan-price-tag-v3',JSON.stringify(state))}
  function loadRecords(){try{const value=JSON.parse(localStorage.getItem(RECORDS_KEY));return Array.isArray(value)?value:[]}catch{return []}}
  function persistRecords(next){try{localStorage.setItem(RECORDS_KEY,JSON.stringify(next));records=next;return true}catch{alert('Не удалось сохранить базу. Возможно, загруженные изображения занимают слишком много места. Экспортируйте базу и удалите лишние QR-изображения.');return false}}
  function clean(v,f='—'){return String(v??'').trim()||f}
  function number(v){const d=String(v??'').replace(/\D/g,'');return d?Number(d).toLocaleString('ru-RU').replace(/\u00a0/g,' '):'—'}
  function stock(){const m=String(state.fields.arrivalDate||'').match(/^\d{4}-(\d{2})-(\d{2})$/);return m?`${m[1]}0${m[2]}`:'—'}
  function out(key){const f=state.fields;if(key==='mileage')return `${number(f.mileage)} км`;if(key==='engine')return `${clean(f.engine)} л.`;if(key==='power')return `${clean(f.power)} л.с.`;if(key==='price')return number(state.toggles.discount?f.salePrice:f.price);if(key==='oldPrice')return `${number(f.price)} ₽`;if(key==='stock')return stock();if(key==='payment')return [...state.payments,state.paymentCustom].filter(Boolean).join(' • ')||'Уточняйте у менеджера';return clean(f[key])}
  function setOutputs(key){if(key==='payment'){renderPayment();return}$$(`[data-out="${key}"]`).forEach(el=>el.textContent=out(key))}
  function icon(path,alt=''){const image=document.createElement('img');image.src=`icons/${path}`;image.alt=alt;image.className='content-icon';return image}
  function renderPayment(){const box=$('[data-out="payment"]');if(!box)return;const paymentIcons={'Наличные':'wallet.png','Кредит':'credit-car.png','Трейд-ин':'trading.png','Обмен':'exchange.png'};const values=[...state.payments,state.paymentCustom].filter(Boolean);box.replaceChildren(...values.map(value=>{const item=document.createElement('span');item.append(icon(paymentIcons[value]||'check.png'),document.createTextNode(value.toUpperCase()));return item}))}
  function renderBenefits(){const box=$('#benefitsOut'),value=clean(state.fields.benefits,'');if(!value){box.replaceChildren();return}const item=document.createElement('span');item.append(icon('check.png'),document.createTextNode(value));box.replaceChildren(item)}
  function renderManager(){const m=state.managers[state.managerIndex]||state.managers[0]||{name:'Менеджер',phone:''};$('#managerName').textContent=m.name;$('#managerPhone').textContent=m.phone}
  function renderQR(){const key=`${state.qrImage||state.fields.qrUrl}`;if(key===qrKey)return;qrKey=key;const box=$('#qrCode');box.innerHTML='';if(state.qrImage){const img=new Image();img.src=state.qrImage;img.alt='QR-код';box.append(img)}else if(state.fields.qrUrl&&window.QRCode)new QRCode(box,{text:state.fields.qrUrl,width:160,height:160,colorDark:'#000',colorLight:'#fff',correctLevel:QRCode.CorrectLevel.M})}
  function applyToggle(name){const card=$('#priceCard'),on=!!state.toggles[name];const map={labels:'hide-labels',discount:'hide-discount',saleType:'hide-sale',status:'hide-status',benefits:'hide-benefits',payment:'hide-payment',stock:'hide-stock',qr:'hide-qr'};if(map[name])card.classList.toggle(map[name],!on);if(name==='mono')card.classList.toggle('mono',on);$$(`[data-control="${name}"]`).forEach(el=>el.classList.toggle('control-off',!on));if(name==='discount'){setOutputs('price');setOutputs('oldPrice')}save()}
  function renderAll(){['brand','model','trim','year','mileage','transmission','fuel','engine','power','drive','price','oldPrice','saleType','status','stock','payment'].forEach(setOutputs);renderBenefits();renderManager();renderQR();Object.keys(state.toggles).forEach(applyToggle);$('#priceCard').classList.toggle('hide-trim',!String(state.fields.trim||'').trim());save()}
  function initSelect(select){const key=select.dataset.select,val=state.fields[key];const custom=$(`[data-custom="${key}"]`),slot=custom?.closest('.custom-slot');if([...select.options].some(o=>o.value===val)){select.value=val;slot?.classList.remove('open')}else{select.value='__custom';if(custom)custom.value=val||'';slot?.classList.add('open')}}
  function renderManagerSelect(){const s=$('#managerSelect');s.replaceChildren(...state.managers.map((m,i)=>{const o=document.createElement('option');o.value=i;o.textContent=`${m.name} — ${m.phone}`;return o}));s.value=Math.min(state.managerIndex,state.managers.length-1)}
  function hydrate(){$$('[data-field]').forEach(el=>{if(state.fields[el.dataset.field]!=null)el.value=state.fields[el.dataset.field]});$$('[data-select]').forEach(initSelect);$$('[data-toggle]').forEach(el=>el.checked=!!state.toggles[el.dataset.toggle]);$$('[data-payment]').forEach(el=>el.checked=state.payments.includes(el.dataset.payment));$('#customPaymentToggle').checked=!!state.paymentCustom;$('#customPayment').value=state.paymentCustom||'';$('#customPayment').closest('.custom-slot').classList.toggle('open',!!state.paymentCustom);renderManagerSelect();renderAll()}
  function make(tag,className,text){const el=document.createElement(tag);if(className)el.className=className;if(text!=null)el.textContent=text;return el}
  function recordPrice(record){const data=normalizeState(record.data),fields=data.fields;return number(data.toggles.discount?fields.salePrice:fields.price)}
  function recordStock(record){const data=normalizeState(record.data),value=String(data.fields.arrivalDate||'').match(/^\d{4}-(\d{2})-(\d{2})$/);return value?`${value[1]}0${value[2]}`:'—'}
  function recordManager(record){const data=normalizeState(record.data),list=data.managers;return list[data.managerIndex]||list[0]||{name:'Менеджер'}}
  function formatSavedDate(value){try{return new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(value))}catch{return ''}}
  function updateEditorContext(){const record=records.find(item=>item.id===currentRecordId);$('#editorHeading').textContent=record?`${clean(state.fields.brand,'')} ${clean(state.fields.model,'')}`.trim():'Новый ценник';$('#saveTagBtn').textContent=record?'Сохранить изменения':'Сохранить ценник';$('#draftStatus').textContent=record?'● Открыт сохранённый ценник':'● Черновик сохранён'}
  function switchView(name){$$('[data-view-panel]').forEach(panel=>panel.hidden=panel.dataset.viewPanel!==name);$$('[data-view]').forEach(button=>button.classList.toggle('active',button.dataset.view===name));if(name==='library')renderLibrary()}
  function createFact(label,value){const cell=make('span');cell.append(make('span','',label),make('strong','',value));return cell}
  function createSavedCard(record){const data=normalizeState(record.data),fields=data.fields,card=make('article','saved-card');const head=make('div','saved-card-head'),badge=make('span','saved-card-badge',fields.saleType||'БЕЗ ПЛАШКИ'),stockLabel=make('span','saved-card-stock',`№ ${recordStock(record)}`);head.append(badge,stockLabel);const title=make('h2','',`${clean(fields.brand,'')} ${clean(fields.model,'')}`.trim()),trim=make('p','saved-card-trim',fields.trim||'Без комплектации'),facts=make('div','saved-card-facts');facts.append(createFact('ГОД',clean(fields.year)),createFact('ПРОБЕГ',`${number(fields.mileage)} км`),createFact('КПП',clean(fields.transmission)),createFact('ДВИГАТЕЛЬ',`${clean(fields.engine)} л. / ${clean(fields.power)} л.с.`));const price=make('div','saved-card-price',`${recordPrice(record)} ₽`),manager=recordManager(record),meta=make('div','saved-card-meta');meta.append(make('span','',manager.name||'Менеджер'),make('span','',formatSavedDate(record.updatedAt)));const actions=make('div','saved-card-actions'),edit=make('button','primary','Открыть и изменить'),duplicate=make('button','','Дублировать'),remove=make('button','danger','Удалить');edit.type=duplicate.type=remove.type='button';edit.addEventListener('click',()=>openRecord(record.id));duplicate.addEventListener('click',()=>duplicateRecord(record.id));remove.addEventListener('click',()=>removeRecord(record.id));actions.append(edit,duplicate,remove);card.append(head,title,trim,facts,price,meta,actions);return card}
  function renderLibrary(){const grid=$('#savedGrid'),sorted=[...records].sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)));grid.replaceChildren(...sorted.map(createSavedCard));$('#savedEmpty').hidden=sorted.length>0;grid.hidden=sorted.length===0;$('#savedCount').textContent=records.length;updateEditorContext()}
  function saveCurrentRecord(){const now=new Date().toISOString(),existing=records.find(item=>item.id===currentRecordId),record={id:existing?.id||(crypto.randomUUID?.()||`tag-${Date.now()}-${Math.random().toString(16).slice(2)}`),createdAt:existing?.createdAt||now,updatedAt:now,data:copy(state)},next=existing?records.map(item=>item.id===record.id?record:item):[record,...records];if(!persistRecords(next))return;currentRecordId=record.id;renderLibrary();updateEditorContext();$('#saveTagBtn').textContent='Сохранено';setTimeout(updateEditorContext,900)}
  function openRecord(id){const record=records.find(item=>item.id===id);if(!record)return;state=normalizeState(copy(record.data));currentRecordId=id;qrKey='';hydrate();updateEditorContext();switchView('editor')}
  function startNewRecord(){state=copy(defaults);currentRecordId=null;qrKey='';hydrate();updateEditorContext();switchView('editor')}
  function duplicateRecord(id){const source=records.find(item=>item.id===id);if(!source)return;const now=new Date().toISOString(),duplicate={id:crypto.randomUUID?.()||`tag-${Date.now()}-${Math.random().toString(16).slice(2)}`,createdAt:now,updatedAt:now,data:copy(source.data)};if(persistRecords([duplicate,...records]))renderLibrary()}
  function removeRecord(id){const record=records.find(item=>item.id===id);if(!record||!confirm(`Удалить ценник «${clean(record.data?.fields?.brand,'')} ${clean(record.data?.fields?.model,'')}»?`))return;const next=records.filter(item=>item.id!==id);if(!persistRecords(next))return;if(currentRecordId===id)currentRecordId=null;renderLibrary();updateEditorContext()}
  function exportRecords(){const payload={version:1,exportedAt:new Date().toISOString(),records};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download='price-tags.json';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  async function importRecords(file){try{const parsed=JSON.parse(await file.text()),source=Array.isArray(parsed)?parsed:parsed.records;if(!Array.isArray(source))throw new Error();const imported=source.filter(item=>item&&typeof item==='object').map(item=>{const now=new Date().toISOString();return {id:String(item.id||crypto.randomUUID?.()||`tag-${Date.now()}-${Math.random().toString(16).slice(2)}`),createdAt:item.createdAt||now,updatedAt:item.updatedAt||now,data:normalizeState(item.data||item.state||item)}}),byId=new Map(records.map(item=>[item.id,item]));imported.forEach(item=>byId.set(item.id,item));if(persistRecords([...byId.values()])){renderLibrary();alert(`Импортировано ценников: ${imported.length}`)}}catch{alert('Не удалось прочитать файл. Выберите корректный price-tags.json.')}}
  async function loadProjectRecords(){if(records.length||location.protocol==='file:')return;try{const response=await fetch('price-tags.json',{cache:'no-store'});if(!response.ok)return;const parsed=await response.json();if(Array.isArray(parsed.records)&&parsed.records.length){persistRecords(parsed.records);renderLibrary()}}catch{}}
  $$('[data-field]').forEach(el=>el.addEventListener('input',()=>{const k=el.dataset.field;state.fields[k]=el.value;if(k==='brand'||k==='model'||k==='year'||k==='fuel'||k==='drive')setOutputs(k);if(k==='trim'){$('#priceCard').classList.toggle('hide-trim',!el.value.trim());setOutputs('trim')}if(k==='mileage')setOutputs('mileage');if(k==='engine')setOutputs('engine');if(k==='power')setOutputs('power');if(k==='price'){setOutputs('oldPrice');if(!state.toggles.discount)setOutputs('price')}if(k==='salePrice'&&state.toggles.discount)setOutputs('price');if(k==='benefits')renderBenefits();if(k==='arrivalDate')setOutputs('stock');if(k==='qrUrl'){state.qrImage='';qrKey='';renderQR()}save()}));
  $$('[data-select]').forEach(select=>select.addEventListener('change',()=>{const k=select.dataset.select,custom=$(`[data-custom="${k}"]`),slot=custom.closest('.custom-slot');if(select.value==='__custom'){slot.classList.add('open');state.fields[k]=custom.value;custom.focus()}else{slot.classList.remove('open');state.fields[k]=select.value;setOutputs(k)}save()}));
  $$('[data-custom]').forEach(el=>el.addEventListener('input',()=>{state.fields[el.dataset.custom]=el.value;setOutputs(el.dataset.custom);save()}));
  $$('[data-toggle]').forEach(el=>el.addEventListener('change',()=>{state.toggles[el.dataset.toggle]=el.checked;applyToggle(el.dataset.toggle)}));
  $$('[data-payment]').forEach(el=>el.addEventListener('change',()=>{state.payments=$$('[data-payment]:checked').map(x=>x.dataset.payment);setOutputs('payment');save()}));
  $('#customPaymentToggle').addEventListener('change',e=>{const slot=$('#customPayment').closest('.custom-slot');slot.classList.toggle('open',e.target.checked);if(!e.target.checked){state.paymentCustom='';$('#customPayment').value='';setOutputs('payment');save()}else $('#customPayment').focus()});
  $('#customPayment').addEventListener('input',e=>{state.paymentCustom=e.target.value.trim();setOutputs('payment');save()});
  $('#managerSelect').addEventListener('change',e=>{state.managerIndex=Number(e.target.value);renderManager();save()});
  $('#qrUpload').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{state.qrImage=reader.result;qrKey='';renderQR();save()};reader.readAsDataURL(file)});
  $('#printBtn').addEventListener('click',()=>window.print());
  $('#saveTagBtn').addEventListener('click',saveCurrentRecord);
  $('#resetBtn').addEventListener('click',()=>{if(confirm('Начать новый ценник? Текущий черновик будет заменён.'))startNewRecord()});
  $('#newTagBtn').addEventListener('click',startNewRecord);
  $('#exportTagsBtn').addEventListener('click',exportRecords);
  $('#importTagsBtn').addEventListener('click',()=>$('#importTagsInput').click());
  $('#importTagsInput').addEventListener('change',e=>{const file=e.target.files[0];if(file)importRecords(file);e.target.value=''});
  $$('[data-view]').forEach(button=>button.addEventListener('click',()=>switchView(button.dataset.view)));
  function editManagers(){const list=$('#managerList');list.replaceChildren(...state.managers.map((m,i)=>{const row=document.createElement('div');row.className='manager-edit';const n=document.createElement('input');n.value=m.name;const p=document.createElement('input');p.value=m.phone;const b=document.createElement('button');b.type='button';b.textContent='×';b.onclick=()=>{state.managers.splice(i,1);editManagers()};row.append(n,p,b);return row}))}
  $('#manageBtn').addEventListener('click',()=>{editManagers();$('#managerDialog').showModal()});
  $('#addManagerBtn').addEventListener('click',()=>{state.managers.push({name:'Новый менеджер',phone:'+7 ('});editManagers()});
  $('#saveManagersBtn').addEventListener('click',()=>{state.managers=$$('.manager-edit').map(r=>({name:r.children[0].value.trim()||'Менеджер',phone:r.children[1].value.trim()}));if(!state.managers.length)state.managers=copy(defaults.managers);state.managerIndex=Math.min(state.managerIndex,state.managers.length-1);renderManagerSelect();renderManager();save()});
  addEventListener('message',event=>{
    if(event.origin!==location.origin||event.data?.type!=='TITAN_PRICE_TAG_LOAD')return;
    const vehicle=event.data.vehicle||{},company=event.data.company||{};
    state=normalizeState({...state,fields:{...state.fields,
      brand:vehicle.brand||'',model:vehicle.model||'',trim:vehicle.generation||'',year:vehicle.year||'',
      mileage:vehicle.mileage||'',transmission:vehicle.transmission||'',fuel:vehicle.fuel_type||'',
      engine:vehicle.engine_volume||'',power:vehicle.engine_power||'',drive:vehicle.drive_type||'',
      price:vehicle.sale_price||vehicle.market_price||'',salePrice:vehicle.sale_price||'',
      benefits:vehicle.notes||'',qrUrl:vehicle.source_url||''
    }});
    if(Array.isArray(company.managers)&&company.managers.length){state.managers=company.managers;state.managerIndex=0;}
    currentRecordId=null;qrKey='';hydrate();updateEditorContext();switchView('editor');
    $('#companyLegalName').textContent=company.legal_name||'ТИТАН АВТО';
    $('#companyRegistration').textContent=[company.ogrn&&`ОГРН ${company.ogrn}`,company.inn&&`ИНН ${company.inn}`,company.kpp&&`КПП ${company.kpp}`].filter(Boolean).join(' | ')||'Реквизиты не заполнены';
    $('#companyAddress').textContent=company.address||'Адрес не заполнен';
    $('#companyBank').textContent=[company.phone,company.bank_name,company.bik&&`БИК ${company.bik}`].filter(Boolean).join(' | ')||'Контакты и банк не заполнены';
    document.title=`Ценник ${vehicle.vehicle_id||''} — ТИТАН АВТО`;
  });
  hydrate();
  renderLibrary();
  updateEditorContext();
  loadProjectRecords();
})();
